dt: "100secs"
apply_limiter: false
ode_algo: SSP333
hyperdiff: "CAM_SE"
dt_save_state_to_disk: "10days"
t_end: "300days"
h_elem: 16
z_elem: 63
max_newton_iters_ode: 3
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
vert_diff: "true"
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
forcing: "held_suarez"
job_id: "dt_SSP_nolim_CD_iter3_100secs"
