[C_E]
alias = "C_E"
value = 0.044
type = "float"

[EDMF_surface_area]
alias = "surface_area"
value = 0.1
type = "float"

[EDMF_min_area]
alias = "min_area"
value = 1.0e-3
type = "float"
description = "Minimum area fraction per updraft. Parameter not described in the literature."

[entr_coeff]
alias = "entr_coeff"
value = 0.1
type = "float"
