[zd_rayleigh]
alias = "zd_rayleigh"
value = 35000.0
type = "float"

[alpha_rayleigh_uh]
alias = "alpha_rayleigh_uh"
value = 0.0
type = "float"

[precipitation_timescale]
alias = "Ï„_precip"
value = 600
type = "float"

[entr_tau]
alias = "entr_tau"
value = 0.002
type = "float"

[entr_coeff]
alias = "entr_coeff"
value = 0
type = "float"

[detr_tau]
alias = "detr_tau"
value = 0
type = "float"

[detr_buoy_coeff]
alias = "detr_buoy_coeff"
value = 0.12
type = "float"

[detr_vertdiv_coeff]
alias = "detr_vertdiv_coeff"
value = 0
type = "float"

[min_area_limiter_scale]
alias = "min_area_limiter_scale"
value = 0
type = "float"

[max_area_limiter_scale]
alias = "max_area_limiter_scale"
value = 0
type = "float"
