[EDMF_surface_area]
alias = "surface_area"
value = 0.1
type = "float"

[EDMF_min_area]
alias = "min_area"
value = 1.0e-3
type = "float"

[entr_tau]
alias = "entr_tau"
value = 0
type = "float"

[entr_coeff]
alias = "entr_coeff"
value = 0.1
type = "float"

[detr_tau]
alias = "detr_tau"
value = 0
type = "float"
