[EDMF_surface_area]
value = 0.1

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_inv_tau]
value = 0

[entr_coeff]
value = 0.1

[min_area_limiter_scale]
value = 0.001

[min_area_limiter_power]
value = 10

[detr_inv_tau]
value = 0

[detr_coeff]
value = 2e-3

[detr_buoy_coeff]
value = 0.3

[detr_vertdiv_coeff]
value = 0.6

[max_area_limiter_scale]
value = 0.01
