[C_E]
value = 0.0176

[EDMF_surface_area]
value = 0.1

[EDMF_min_area]
value = 1.0e-5

[min_area_limiter_scale]
value = 1.201

[min_area_limiter_power]
value = 1089

[max_area_limiter_scale]
value = 0

[pressure_normalmode_drag_coeff]
value = 3.963

[pressure_normalmode_buoy_coeff1]
value = 0.857

[mixing_length_eddy_viscosity_coefficient]
value = 0.041

[mixing_length_diss_coeff]
value = 0.174

[mixing_length_static_stab_coeff]
value = 0.292

[mixing_length_tke_surf_scale]
value = 9.609

[mixing_length_Prandtl_number_0]
value = 0.515
