[EDMF_surface_area]
value = 0.1

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_inv_tau]
value = 0.0002

[entr_coeff]
value = 0.3

[min_area_limiter_scale]
value = 0

[min_area_limiter_power]
value = 10

[detr_inv_tau]
value = 0

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[detr_massflux_vertdiv_coeff]
value = 1

[max_area_limiter_scale]
value = 0

[pressure_normalmode_drag_coeff]
value = 40.0

[sde_entr_tau]
value = 0.1
type = "float"

[sde_entr_sigma]
value = 0.0001
type = "float"

[sde_entr_mu]
value = 0.001
type = "float"

[sde_detr_tau]
value = 0.1
type = "float"

[sde_detr_sigma]
value = 0.0001
type = "float"

[sde_detr_mu]
value = 0.001
type = "float"
