agents:
  queue: central
  modules: julia/1.8.5 cuda/11.8 ucx/1.14.1_cuda-11.8 openmpi/4.1.5_cuda-11.8 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100


timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
      slurm_mem: 8G
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted resolution AMIP long runs"

    steps:

      # - label: ":computer: no lim ARS aquaplanet equilmoist clearsky radiation diagnostic edmf"
      #   command:
      #     - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --C_E 0.0176 --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --turbconv diagnostic_edmfx --edmfx_entr_detr true --edmfx_sgs_flux true --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 3e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 100days --job_id aquaplanet_equil_clearsky_diagedmf --dt_save_to_sol Inf --dt_save_to_disk 1days --FLOAT_TYPE Float64 --apply_limiter false
      #     - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir aquaplanet_equil_clearsky_diagedmf --out_dir aquaplanet_equil_clearsky_diagedmf
      #     - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir aquaplanet_equil_clearsky_diagedmf --fig_dir aquaplanet_equil_clearsky_diagedmf --case_name aquaplanet
      #   artifact_paths: "aquaplanet_equil_clearsky_diagedmf/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 32
      #     slurm_mem_per_cpu: 16GB
      
      # - label: ":computer: no lim ARS aquaplanet equilmoist clearsky radiation diagnostic edmf dt50"
      #   command:
      #     - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --C_E 0.0176 --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --turbconv diagnostic_edmfx --edmfx_entr_detr true --edmfx_sgs_flux true --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 3e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 50secs --t_end 100days --job_id aquaplanet_equil_clearsky_diagedmf_dt50 --dt_save_to_sol Inf --dt_save_to_disk 1days --FLOAT_TYPE Float64 --apply_limiter false
      #     - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir aquaplanet_equil_clearsky_diagedmf_dt50 --out_dir aquaplanet_equil_clearsky_diagedmf_dt50
      #     - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir aquaplanet_equil_clearsky_diagedmf_dt50 --fig_dir aquaplanet_equil_clearsky_diagedmf_dt50 --case_name aquaplanet
      #   artifact_paths: "aquaplanet_equil_clearsky_diagedmf_dt50/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 32
      #     slurm_mem_per_cpu: 16GB
      
      - label: ":computer: no lim ARS aquaplanet equilmoist clearsky radiation h_elem 24"
        command: >
          srun --cpu-bind=cores 
          nsys profile --trace=mpi,nvtx,cuda --mpi-impl=openmpi --output=aquaplanet_equil_clearsky_ft64/report-%q{PMI_RANK} 
          julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --z_elem 35 --dz_bottom 50 --h_elem 24 --kappa_4 3e15 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 1days --job_id aquaplanet_equil_clearsky_ft64 --dt_save_to_sol Inf --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false
          # - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir aquaplanet_equil_clearsky_ft64 --out_dir aquaplanet_equil_clearsky_ft64
          # - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir aquaplanet_equil_clearsky_ft64 --fig_dir aquaplanet_equil_clearsky_ft64 --case_name aquaplanet
        artifact_paths: "aquaplanet_equil_clearsky_ft64/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 8GB
          slurm_cpus_per_task: 2

     
