env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 96:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Dry and moist BW"

    steps:

      - label: ":computer: dry baroclinic wave (ρe_tot) high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 400secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_highres
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_bw_rhoe_highres --out_dir longrun_bw_rhoe_highres
        artifact_paths: "longrun_bw_rhoe_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: dry SSP baroclinic wave (ρe_tot) high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 350secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_dry_ssp_bw_rhoe_highres --ode_algo SSP333 --max_newton_iters 6
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_dry_ssp_bw_rhoe_highres --out_dir longrun_dry_ssp_bw_rhoe_highres
        artifact_paths: "longrun_dry_ssp_bw_rhoe_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: no lim ARS equilmoist baroclinic wave (ρe_tot) high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 400secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_bw_rhoe_equil_highres --out_dir longrun_bw_rhoe_equil_highres
        artifact_paths: "longrun_bw_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: no lim SSP equilmoist baroclinic wave (ρe_tot) high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 350secs --max_newton_iters 6 --t_end 100days --dt_save_to_disk 10days --job_id longrun_no_lim_ssp_bw_rhoe_equil_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_no_lim_ssp_bw_rhoe_equil_highres --out_dir longrun_no_lim_ssp_bw_rhoe_equil_highres
        artifact_paths: "longrun_no_lim_ssp_bw_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP equilmoist baroclinic wave (ρe_tot) high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 350secs --max_newton_iters 6 --t_end 100days --dt_save_to_disk 10days --job_id longrun_ssp_bw_rhoe_equil_highres --ode_algo SSP333"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp_bw_rhoe_equil_highres --out_dir longrun_ssp_bw_rhoe_equil_highres
        artifact_paths: "longrun_ssp_bw_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

  - group: "Dry and moist HS"

    steps:

      - label: ":computer: dry held suarez (ρe_tot) high resolution hightop"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_max 45e3 --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 400secs --t_end 800days --job_id longrun_hs_rhoe_highres_hightop --dt_save_to_disk 10days
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_hs_rhoe_highres_hightop --out_dir longrun_hs_rhoe_highres_hightop
        artifact_paths: "longrun_hs_rhoe_highres_hightop/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: no lim ARS equilmoist held suarez (ρe_tot) high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 800days --dt_save_to_disk 10days --job_id longrun_no_lim_hs_rhoe_equil_highres --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_no_lim_hs_rhoe_equil_highres --out_dir longrun_no_lim_hs_rhoe_equil_highres
        artifact_paths: "longrun_no_lim_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: no lim SSP equilmoist held suarez (ρe_tot) high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 125secs --max_newton_iters 6 --t_end 800days --dt_save_to_disk 10days --job_id longrun_no_lim_ssp_hs_rhoe_equil_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_no_lim_ssp_hs_rhoe_equil_highres --out_dir longrun_no_lim_ssp_hs_rhoe_equil_highres
        artifact_paths: "longrun_no_lim_ssp_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP equilmoist held suarez (ρe_tot) high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 125secs --max_newton_iters 6 --t_end 800days --dt_save_to_disk 10days --job_id longrun_ssp_hs_rhoe_equil_highres --ode_algo SSP333"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp_hs_rhoe_equil_highres --out_dir longrun_ssp_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

  - group: "Dry and moist aquaplanet"

    steps:

      - label: ":computer: no lim ARS equilmoist aquaplanet (ρe_tot) high resolution clearsky radiation Float64"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_scheme monin_obukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 150secs --t_end 800days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64 --dt_save_to_sol 10days --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64 --out_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64
        artifact_paths: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: no lim SSP equilmoist aquaplanet (ρe_tot) high resolution clearsky radiation Float64"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_scheme monin_obukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 125secs --max_newton_iters 6 --t_end 800days --fps 30 --job_id longrun_no_lim_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64 --dt_save_to_sol 10days --dt_save_to_disk 10days --FLOAT_TYPE Float64 --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_no_lim_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64 --out_dir longrun_no_lim_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64
        artifact_paths: "longrun_no_lim_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP equilmoist aquaplanet (ρe_tot) high resolution clearsky radiation Float64"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_scheme monin_obukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 125secs --max_newton_iters 6 --t_end 800days --fps 30 --job_id longrun_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64 --dt_save_to_sol 10days --dt_save_to_disk 10days --FLOAT_TYPE Float64 --ode_algo SSP333"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64 --out_dir longrun_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64
        artifact_paths: "longrun_ssp_aquaplanet_rhoe_equil_highres_clearsky_ft64/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
