env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 48:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "dry and moist held-suarez"

    steps:

      - label: ":computer: SSP inter2 dt100 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 100secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp2_dt100_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 2 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_dt100_hs_rhoe_equil_highres --out_dir longrun_ssp2_dt100_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp2_dt100_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP inter2 dt150 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp2_dt150_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 2 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_dt150_hs_rhoe_dry_highres --out_dir longrun_ssp2_dt150_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp2_dt150_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
          
      - label: ":computer: SSP inter6 dt300 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp6_dt300_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 6 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp6_dt300_hs_rhoe_equil_highres --out_dir longrun_ssp6_dt300_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp6_dt300_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP inter6 dt300 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp6_dt300_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 6 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp6_dt300_hs_rhoe_dry_highres --out_dir longrun_ssp6_dt300_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp6_dt300_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
          
      - label: ":computer: SSP inter6 dt400 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 400secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp6_dt400_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 6 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp6_dt400_hs_rhoe_equil_highres --out_dir longrun_ssp6_dt400_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp6_dt400_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP inter6 dt400 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 400secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp6_dt400_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 6 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp6_dt400_hs_rhoe_dry_highres --out_dir longrun_ssp6_dt400_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp6_dt400_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
          
      - label: ":computer: SSP inter6 dt200 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 200secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp6_dt200_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 6 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp6_dt200_hs_rhoe_equil_highres --out_dir longrun_ssp6_dt200_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp6_dt200_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64

      - label: ":computer: SSP inter6 dt200 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 200secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_ssp6_dt200_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 6 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp6_dt200_hs_rhoe_dry_highres --out_dir longrun_ssp6_dt200_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp6_dt200_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
