agents:
  queue: central
  slurm_mem_per_cpu: 8G
  modules: julia/1.9.4 cuda/12.2 ucx/1.14.1_cuda-12.2 openmpi/4.1.5_cuda-12.2 nsight-systems/2023.3.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_CPU_TARGET: 'broadwell;skylake;icelake;cascadelake;epyc'
  CONFIG_PATH: "config/longrun_configs"
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_CUDA_MEMORY_POOL: none
  JULIA_MPI_HAS_CUDA: "true"
  MPITRAMPOLINE_LIB: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/lib64/libmpiwrapper.so"
  MPITRAMPOLINE_MPIEXEC: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/bin/mpiwrapperexec"

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"
      - "julia --project=examples artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
      slurm_gpus: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted AMIP resolution long runs"

    steps:

      - label: ":computer: hydrostatic balance (ρe_tot)"
        command:
          - srun julia --color=yes --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name dry_held_suarez
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 32
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_sphere_hydrostatic_balance_rhoe"

      - label: ":computer: lim ARS zalesak baroclinic wave (ρe_tot) equilmoist high resolution"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name moist_baroclinic_wave
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 32GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_zalesak_tracer_energy_bw_rhoe_equil_highres"

      - label: ":computer: SSP baroclinic wave (ρe_tot) equilmoist high resolution centered diff"
        command:
          - "srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name moist_baroclinic_wave
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 32
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_ssp_bw_rhoe_equil_highres"

      - label: ":computer: aquaplanet, equilmoist, high-topped (55km), gray-radiation, vertdiff, high-sponge (35km), helem_16 np_3"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00

      - label: ":computer: aquaplanet (ρe_tot) equilmoist clearsky high resolution (nz63) hightop (55km) rayleigh sponge(35e3, 10)"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky"

      - label: ":computer: aquaplanet (ρe_tot) equilmoist clearsky high resolution (nz63) hightop (55km) rayleigh sponge(35e3, 10) + time-varying insolation"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation"

      - label: ":computer: aquaplanet slab ocean (ρe_tot) equilmoist clearsky high resolution (nz63) hightop (55km) rayleigh sponge(35e3, 10) + time-varying insolation"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation_slabocean"

      - label: ":computer: aquaplanet (ρe_tot) equilmoist clearsky high resolution (nz63) hightop (55km) rayleigh sponge(35e3, 10) + earth topography"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_earth"

  - group: "Low resolution long runs"

    steps:

      - label: ":computer: aquaplanet slab ocean (ρe_tot) equilmoist clearsky low resolution + time-varying insolation"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 8
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equilmoist_0M_clearsky_tvinsolation_slabocean"


  - group: "Experimental long runs"

    steps:

      - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution topography (earth)"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_bw_rhoe_equil_highres_topography_earth"

      - label: ":computer: held suarez (ρe_tot) equilmoist high resolution topography (earth)"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_hs_rhoe_equil_highres_topography_earth"

      - label: ":computer: no lim ARS aquaplanet (ρe_tot) equilmoist high resolution clearsky radiation Float32 (earth)"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir $$JOB_NAME --fig_dir $$JOB_NAME --case_name aquaplanet
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft32_earth"

  - group: "DYAMOND"

    steps:

      - label: ":computer: aquaplanet dyamond"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 32GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_dyamond"

  - group: "AMIP"

    steps:

      - label: ":computer: aquaplanet amip"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir $$JOB_NAME --out_dir $$JOB_NAME
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 20GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_amip"
