env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 48:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted resolution AMIP long runs"

    steps:

      - label: ":computer: topography+edmf test" 
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --turbconv diagnostic_edmfx --edmfx_entr_detr true --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 4e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 365days --job_id aquaplanet_equil_clearsky_diagedmf_ft64_earth --dt_save_to_sol Inf --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false --topography Earth --topo_smoothing true --use_reference_state false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography --out_dir longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography
        artifact_paths: "longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_exclusive: true
          slurm_partition: expansion
          slurm_mem: 0GB
          slurm_ntasks: 128
      
      - label: ":computer: topography+edmf test" 
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --turbconv diagnostic_edmfx --edmfx_entr_detr true --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 4e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 365days --job_id aquaplanet_equil_clearsky_diagedmf_ft64_earth --dt_save_to_sol Inf --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false --topography Earth --topo_smoothing true --use_reference_state false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography --out_dir longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography
        artifact_paths: "longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_partition: expansion
          slurm_exclusive: true
          slurm_ntasks: 256
          slurm_mem: 0GB
      
      - label: ":computer: topography+edmf+up-params test" 
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --turbconv diagnostic_edmfx --edmfx_entr_detr true --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 8e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 200secs --t_end 365days --job_id aquaplanet_equil_clearsky_diagedmf_ft64_earth --dt_save_to_sol Inf --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false --topography Earth --topo_smoothing true --use_reference_state false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography --out_dir longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography
        artifact_paths: "longrun_aquaplanet_rhoe_equil_target_diag-edmfx_topography/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_partition: expansion
          slurm_exclusive: true
          slurm_ntasks: 128
          slurm_mem: 384GB
