env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "dry and moist baroclinic wave h_elem 16"

    steps:

      - label: ":computer: SSP iter1 baroclinic wave (ρe_tot) equilmoist high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 100secs --max_newton_iters 1 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp1_bw_rhoe_equil_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp1_bw_rhoe_equil_highres --out_dir longrun_ssp1_bw_rhoe_equil_highres
        artifact_paths: "longrun_ssp1_bw_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter2 baroclinic wave (ρe_tot) equilmoist high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --max_newton_iters 2 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp2_bw_rhoe_equil_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_bw_rhoe_equil_highres --out_dir longrun_ssp2_bw_rhoe_equil_highres
        artifact_paths: "longrun_ssp2_bw_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter3 baroclinic wave (ρe_tot) equilmoist high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --max_newton_iters 3 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp3_bw_rhoe_equil_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp3_bw_rhoe_equil_highres --out_dir longrun_ssp3_bw_rhoe_equil_highres
        artifact_paths: "longrun_ssp3_bw_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter1 baroclinic wave (ρe_tot) dry high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 100secs --max_newton_iters 1 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp1_bw_rhoe_dry_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp1_bw_rhoe_dry_highres --out_dir longrun_ssp1_bw_rhoe_dry_highres
        artifact_paths: "longrun_ssp1_bw_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter2 baroclinic wave (ρe_tot) dry high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --max_newton_iters 2 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp2_bw_rhoe_dry_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_bw_rhoe_dry_highres --out_dir longrun_ssp2_bw_rhoe_dry_highres
        artifact_paths: "longrun_ssp2_bw_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32     

      - label: ":computer: SSP iter3 baroclinic wave (ρe_tot) dry high resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --max_newton_iters 3 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp3_bw_rhoe_dry_highres --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp3_bw_rhoe_dry_highres --out_dir longrun_ssp3_bw_rhoe_dry_highres
        artifact_paths: "longrun_ssp3_bw_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

  - group: "dry and moist baroclinic wave h_elem 6"

    steps:

      - label: ":computer: SSP iter1 baroclinic wave (ρe_tot) equilmoist low resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --dt 450secs --max_newton_iters 1 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp1_bw_rhoe_equil --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp1_bw_rhoe_equil --out_dir longrun_ssp1_bw_rhoe_equil
        artifact_paths: "longrun_ssp1_bw_rhoe_equil/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter2 baroclinic wave (ρe_tot) equilmoist low resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --dt 450secs --max_newton_iters 2 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp2_bw_rhoe_equil --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_bw_rhoe_equil --out_dir longrun_ssp2_bw_rhoe_equil
        artifact_paths: "longrun_ssp2_bw_rhoe_equil/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter3 baroclinic wave (ρe_tot) equilmoist low resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --dt 450secs --max_newton_iters 3 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp3_bw_rhoe_equil --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp3_bw_rhoe_equil --out_dir longrun_ssp3_bw_rhoe_equil
        artifact_paths: "longrun_ssp3_bw_rhoe_equil/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter1 baroclinic wave (ρe_tot) dry low resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --dt 580secs --max_newton_iters 1 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp1_bw_rhoe_dry --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp1_bw_rhoe_dry --out_dir longrun_ssp1_bw_rhoe_dry
        artifact_paths: "longrun_ssp1_bw_rhoe_dry/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP iter2 baroclinic wave (ρe_tot) dry low resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --dt 580secs --max_newton_iters 2 --t_end 10days --dt_save_to_disk 1days --job_id longrun_ssp2_bw_rhoe_dry --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_bw_rhoe_dry --out_dir longrun_ssp2_bw_rhoe_dry
        artifact_paths: "longrun_ssp2_bw_rhoe_dry/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32     

      - label: ":computer: SSP iter3 baroclinic wave (ρe_tot) dry low resolution"
        command:
          - "mpiexec julia --project=examples examples/hybrid/driver.jl --dt 580secs --max_newton_iters 3 --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp3_bw_rhoe_dry --ode_algo SSP333 --apply_limiter false"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp3_bw_rhoe_dry --out_dir longrun_ssp3_bw_rhoe_dry
        artifact_paths: "longrun_ssp3_bw_rhoe_dry/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32  


  - group: "dry and moist held-suarez"

    steps:

      - label: ":computer: SSP inter1 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp1_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 1 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp1_hs_rhoe_equil_highres --out_dir longrun_ssp1_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp1_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP inter2 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp2_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 2 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_hs_rhoe_equil_highres --out_dir longrun_ssp2_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp2_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP inter3 held suarez (ρe_tot) equilmoist high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp3_hs_rhoe_equil_highres --ode_algo SSP333 --max_newton_iters 3 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp3_hs_rhoe_equil_highres --out_dir longrun_ssp3_hs_rhoe_equil_highres
        artifact_paths: "longrun_ssp3_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP inter1 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp1_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 1 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp1_hs_rhoe_dry_highres --out_dir longrun_ssp1_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp1_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP inter2 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp2_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 2 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp2_hs_rhoe_dry_highres --out_dir longrun_ssp2_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp2_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32

      - label: ":computer: SSP inter3 held suarez (ρe_tot) dry high resolution"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 150secs --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp3_hs_rhoe_dry_highres --ode_algo SSP333 --max_newton_iters 3 --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_ssp3_hs_rhoe_dry_highres --out_dir longrun_ssp3_hs_rhoe_dry_highres
        artifact_paths: "longrun_ssp3_hs_rhoe_dry_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32
