agents:
  queue: new-central
  slurm_mem_per_cpu: 8G
  modules: climacommon/2024_02_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_CPU_TARGET: 'broadwell;skylake;icelake;cascadelake;epyc'
  CONFIG_PATH: "config/longrun_configs"
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"
      - "julia --project=examples artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
      slurm_gpus: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted AMIP resolution long runs"

    steps:

      # TODO: uncomment when zalesak works
      # - label: ":computer: lim ARS zalesak baroclinic wave (ρe_tot) equilmoist high resolution"
      #   command:
      #     - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
      #   artifact_paths: "$$JOB_NAME/*"
      #   agents:
      #     slurm_ntasks: 32
      #     slurm_mem_per_cpu: 32GB
      #     slurm_time: 24:00:00
      #   env:
      #     JOB_NAME: "longrun_zalesak_tracer_energy_bw_rhoe_equil_highres"

      - label: ":computer: SSP baroclinic wave (ρe_tot) equilmoist high resolution centered diff"
        command:
          - "srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml"
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 32
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_ssp_bw_rhoe_equil_highres"

      - label: ":computer: aquaplanet equilmoist gray radiation + 0M microphysics"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_55km_nz63_gray_0M"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00

      - label: ":computer: aquaplanet equilmoist clearsky radiation + diagnostic edmf diffusion only + 0M microphysics"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_diagedmf_diffonly_0M"

      - label: ":computer: aquaplanet equilmoist clearsky radiation + time-varying insolation + 0M microphysics + slab ocean"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean"

      - label: ":computer: aquaplanet equilmoist clearsky radiation + 0M microphysics + earth topography"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth"

      - label: ":computer: aquaplanet equilmoist clearsky radiation + 1M microphysics"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_1M"

  - group: "Low resolution long runs"

    steps:

      - label: ":computer: low resolution aquaplanet equilmoist clearsky radiation + time-varying insolation + slab ocean"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 8
          slurm_mem_per_cpu: 16GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_rhoe_equil_clearsky_tvinsol_0M_slabocean"

  - group: "DYAMOND"

    steps:

      - label: ":computer: aquaplanet dyamond"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 32GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_dyamond"

  - group: "AMIP"

    steps:

      - label: ":computer: aquaplanet amip"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 20GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "longrun_aquaplanet_amip"

  - group: "atmos-only coupler runs"

    steps:

      - label: ":computer: amip target diagnostic edmf"
        command:
          - srun julia --project=examples examples/hybrid/driver.jl --config_file $CONFIG_PATH/$$JOB_NAME.yml
        artifact_paths: "$$JOB_NAME/*"
        agents:
          slurm_ntasks: 64
          slurm_mem_per_cpu: 20GB
          slurm_time: 24:00:00
        env:
          JOB_NAME: "amip_target_diagedmf"
