env:
  JULIA_VERSION: "1.7.2"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Core Long runs (central difference)"

    steps:

      # TODO: Add all milestone long simulation runs

      - label: ":computer: held suarez (ρe_tot)"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --t_end 1200days --fps 30 --job_id longrun_hs_rhoe --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: held suarez (ρe_tot) equilmoist"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --microphy 0M --dt 250secs --t_end 800days --fps 30 --job_id longrun_hs_rhoe_equil --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_equil/*"
        agents:
          slurm_cpus_per_task: 8
      
      - label: ":computer: held suarez (ρe_tot) equilmoist no_save_to_sol"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --microphy 0M --dt 250secs --t_end 800days --fps 30 --job_id longrun_hs_rhoe_equil_nosavetosol --dt_save_to_sol Inf --dt_save_to_disk 10days --post_process false"
        artifact_paths: "longrun_hs_rhoe_equil_nosavetosol/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: held suarez (ρe_tot) equilmoist monin_obukhov Float64"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme monin_obukhov --microphy 0M --dt 250secs --t_end 800days --fps 30 --job_id longrun_hs_rhoe_equil_mo_ft64 --dt_save_to_sol 1days --dt_save_to_disk 10days --FLOAT_TYPE Float64"
        artifact_paths: "longrun_hs_rhoe_equil_mo_ft64/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: aquaplanet (ρe_tot) equilmoist clearsky radiation monin_obukhov Float64"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --vert_diff true --surface_scheme monin_obukhov --moist equil --rad clearsky --microphy 0M --viscous_sponge true --kappa_2_sponge 1e7 --dt 200secs --t_end 600days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_clearsky_mo_ft64 --dt_save_to_sol 1days --dt_save_to_disk 10days --FLOAT_TYPE Float64"
        artifact_paths: "longrun_aquaplanet_rhoe_equil_clearsky_mo_ft64/*"
        agents:
          slurm_cpus_per_task: 8
      - label: ":computer: aquaplanet (ρe_tot) equilmoist gray radiation"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --vert_diff true --moist equil --rad gray --microphy 0M --dt 200secs --t_end 600days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_gray --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_aquaplanet_rhoe_equil_gray/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: aquaplanet (ρe_tot) equilmoist clearsky radiation"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --vert_diff true --moist equil --rad clearsky --microphy 0M --viscous_sponge true --kappa_2_sponge 1e7 --dt 200secs --t_end 600days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_clearsky --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_aquaplanet_rhoe_equil_clearsky/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: aquaplanet (ρe_tot) equilmoist allsky radiation"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --vert_diff true --moist equil --rad allskywithclear --microphy 0M --viscous_sponge true --kappa_2_sponge 1e7 --dt 200secs --t_end 600days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_allsky --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_aquaplanet_rhoe_equil_allsky/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: held suarez (ρe_int)"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --energy_name rhoe_int --t_end 1200days --fps 30 --job_id longrun_hs_rhoeint --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoeint/*"
        agents:
          slurm_cpus_per_task: 8

  - group: "Core Long runs (third-order upwinding)"

    steps:

      - label: ":computer: held suarez (ρe_tot) third order"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --upwinding third_order --dt 350secs --t_end 1200days --fps 30 --job_id longrun_hs_rhoe_third --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_third/*"
        agents:
          slurm_cpus_per_task: 8
      
      - label: ":computer: held suarez (ρe_tot) third order topography"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --upwinding third_order --dt 300secs --t_end 1200days --fps 30 --job_id longrun_hs_rhoe_third --dt_save_to_sol 1days --dt_save_to_disk 10days --topography DCMIP200"
        artifact_paths: "longrun_hs_rhoe_third/*"
        agents:
          slurm_cpus_per_task: 8


      - label: ":computer: held suarez (ρe_tot) equilmoist third order"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --upwinding third_order --forcing held_suarez --moist equil --vert_diff true --microphy 0M --dt 150secs --t_end 600days --fps 30 --job_id longrun_hs_rhoe_equil_third --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_equil_third/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: aquaplanet (ρe_tot) equilmoist gray radiation third order"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --upwinding third_order --vert_diff true --moist equil --rad gray --microphy 0M --dt 200secs --t_end 600days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_gray_third --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_aquaplanet_rhoe_equil_gray_third/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: aquaplanet (ρe_tot) equilmoist clearsky radiation third order"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --upwinding third_order --vert_diff true --moist equil --rad clearsky --microphy 0M --viscous_sponge true --kappa_2_sponge 1e7 --dt 150secs --t_end 600days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_clearsky_third --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_aquaplanet_rhoe_equil_clearsky_third/*"
        agents:
          slurm_cpus_per_task: 8

  - group: "Experimental Long runs"

    steps:

      - label: ":computer: held suarez (ρe_tot) hightop"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --z_max 45e3 --z_elem 25 --dt 300secs --t_end 600days --fps 30 --job_id longrun_hs_rhoe_hightop --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_hightop/*"
        agents:
          slurm_cpus_per_task: 8

      - label: ":computer: held suarez (ρe_tot) hightop third order"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --upwinding third_order --forcing held_suarez --z_max 45e3 --z_elem 25 --dt 300secs --t_end 600days --fps 30 --job_id longrun_hs_rhoe_hightop_third --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_hightop_third/*"
        agents:
          slurm_cpus_per_task: 8
      
      - label: ":computer: held suarez (ρe_tot) equilmoist hightop"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --microphy 0M --z_max 45e3 --z_elem 25 --dt 200secs --t_end 600days --fps 30 --job_id longrun_hs_rhoe_equil_hightop --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_equil_hightop/*"
        agents:
          slurm_cpus_per_task: 8
      
      - label: ":computer: held suarez (ρe_tot) equilmoist hightop sponge"
        command: "julia --color=yes --project=examples --threads=8 examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --microphy 0M --z_max 45e3 --z_elem 25 --rayleigh_sponge true --zd_rayleigh 30e3 --alpha_rayleigh_uh 0 --dt 200secs --t_end 600days --fps 30 --job_id longrun_hs_rhoe_equil_hightop_sponge --dt_save_to_sol 1days --dt_save_to_disk 10days"
        artifact_paths: "longrun_hs_rhoe_equil_hightop_sponge/*"
        agents:
          slurm_cpus_per_task: 8

  - group: "Targeted resolution AMIP long runs"
  
    steps:

      - label: ":computer: held suarez (ρe_tot) high resolution"
        command: "mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --z_elem 45 --dz_bottom 30 --h_elem 12 --kappa_4 7e15 --dt 200secs --t_end 600days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_highres"
        artifact_paths: "longrun_hs_rhoe_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 128

      - label: ":computer: held suarez (ρe_tot) equilmoist high resolution"
        command: "mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --microphy 0M --z_elem 45 --dz_bottom 30 --h_elem 12 --kappa_4 7e15 --dt 50secs --t_end 150days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_equil_highres"
        artifact_paths: "longrun_hs_rhoe_equil_highres/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 256
