env:
  JULIA_VERSION: "1.8.0"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted resolution AMIP long runs"

    steps:
    
      - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution dt200"
        command: "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --microphy 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 200secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres_dt200"
        artifact_paths: "longrun_bw_rhoe_equil_highres_dt200/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 128

      # - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution"
      #   command: "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --microphy 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 50secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres"
      #   artifact_paths: "longrun_bw_rhoe_equil_highres/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 128
      
      - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution third"
        command: "mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --microphy 0M --tracer_upwinding third_order --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 200secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres_third_ars343"
        artifact_paths: "longrun_bw_rhoe_equil_highres_third/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 128
      
      - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution ars343"
        command: "mpiexec julia --project=examples examples/hybrid/driver.jl --ode_algo ARS343 --moist equil --microphy 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 200secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres_ars343"
        artifact_paths: "longrun_bw_rhoe_equil_highres_ars343/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 128
      
      - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution third ars343"
        command: "mpiexec julia --project=examples examples/hybrid/driver.jl --ode_algo ARS343 --moist equil --microphy 0M --tracer_upwinding third_order --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 200secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres_third_ars343"
        artifact_paths: "longrun_bw_rhoe_equil_highres_third_ars343/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 128

      # - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution zalesak ars343"
      #   command: "mpiexec julia --project=examples examples/hybrid/driver.jl --ode_algo ARS343 --moist equil --microphy 0M --tracer_upwinding zalesak --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 50secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres_zalesak_ars343"
      #   artifact_paths: "longrun_bw_rhoe_equil_highres_zalesak_ars343/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 128

      # - label: ":computer: held suarez (ρe_tot) equilmoist high resolution"
      #   command: "mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --microphy 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 50secs --t_end 200days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_equil_highres"
      #   artifact_paths: "longrun_hs_rhoe_equil_highres/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 128
      
      # - label: ":computer: held suarez (ρe_tot) equilmoist high resolution ars343"
      #   command: "mpiexec julia --project=examples examples/hybrid/driver.jl --ode_algo ARS343 --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --microphy 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 50secs --t_end 200days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_equil_highres_ars343"
      #   artifact_paths: "longrun_hs_rhoe_equil_highres_ars343/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 128
      
      # - label: ":computer: held suarez (ρe_tot) equilmoist high resolution third ars343"
      #   command: "mpiexec julia --project=examples examples/hybrid/driver.jl --ode_algo ARS343 --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --microphy 0M --tracer_upwinding third_order --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 50secs --t_end 200days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_equil_highres_third_ars343"
      #   artifact_paths: "longrun_hs_rhoe_equil_highres_third_ars343/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 128

      # - label: ":computer: held suarez (ρe_tot) equilmoist high resolution zalesak ars343"
      #   command: "mpiexec julia --project=examples examples/hybrid/driver.jl --ode_algo ARS343 --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --microphy 0M --tracer_upwinding zalesak --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 50secs --t_end 200days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_equil_highres_zalesak_ars343"
      #   artifact_paths: "longrun_hs_rhoe_equil_highres_zalesak_ars343/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #   agents:
      #     slurm_ntasks: 128
