rad: "allskywithclear"
rayleigh_sponge: true
zd_rayleigh: 30000.0
orographic_gravity_wave: "raw_topo"
z_elem: 25
dt: "1secs"
surface_setup: "DefaultMoninObukhov"
t_end: "1mins"
non_orographic_gravity_wave: true
dz_bottom: 300.0
vert_diff: "true"
idealized_insolation: false
z_max: 45000.0
precip_model: "0M"
alpha_rayleigh_uh: 0.0
job_id: "flame_perf_gw"
moist: "equil"
