moist: "equil"
apply_limiter: true
z_elem: 25
dt: "1secs"
surface_setup: "DefaultExchangeCoefficients"
t_end: "10secs"
vert_diff: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
h_elem: 12
forcing: "held_suarez"
precip_model: "0M"
dt_save_to_sol: "Inf"
rad: "allskywithclear"
log_progress: false
rad: ~
apply_limiter: false
dt_save_state_to_disk: "10secs"
precip_model: ~
turbconv: "edmf"
FLOAT_TYPE: "Float64"
z_stretch: false
