moist: "equil"
z_elem: 25
dt: "1secs"
surface_setup: "DefaultExchangeCoefficients"
t_end: "10secs"
vert_diff: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
h_elem: 12
forcing: "held_suarez"
precip_model: "0M"
dt_save_to_sol: "Inf"
log_progress: false
apply_limiter: false
precip_model: "0M"
h_elem: 12
initial_condition: "MoistBaroclinicWave"
t_end: "1mins"
rad: ~
