moist: "equil"
apply_limiter: true
z_elem: 25
dt: "1secs"
surface_setup: "DefaultExchangeCoefficients"
t_end: "10secs"
vert_diff: "true"
implicit_diffusion: true
approximate_linear_solve_iters: 2
h_elem: 12
forcing: "held_suarez"
precip_model: "0M"
dt_save_to_sol: "Inf"
rad: "allskywithclear"
warn_allocations_diagnostics: true
log_progress: false
dz_bottom: 300.0
rayleigh_sponge: true
toml:
  - "toml/flame_perf_gw.toml"
orographic_gravity_wave: "raw_topo"
idealized_insolation: false
non_orographic_gravity_wave: true
z_max: 55000.0
