job_id: flame_perf_target_prognostic_edmfx_aquaplanet
surface_setup: DefaultExchangeCoefficients
rad: gray
vert_diff: "false"
turbconv: prognostic_edmfx 
implicit_diffusion: true
implicit_sgs_advection: true
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil 
precip_model: 0M
dt: 10secs 
t_end: 1hours 
dt_save_state_to_disk: 600secs
toml: [toml/prognostic_edmfx_box.toml]
