moist: "equil"
apply_limiter: true
surface_setup: "DefaultExchangeCoefficients"
t_end: "10secs"
vert_diff: "true"
implicit_diffusion: true
approximate_linear_solve_iters: 2
forcing: "held_suarez"
precip_model: "0M"
rad: "allskywithclear"
log_progress: false
h_elem: 12
initial_condition: "DryBaroclinicWave"
t_end: "1mins"
z_elem: 25
dt: "1secs"
dt_save_to_sol: "Inf"
