surface_setup: "DefaultExchangeCoefficients"
vert_diff: "true"
implicit_diffusion: true
approximate_linear_solve_iters: 2
forcing: "held_suarez"
rad: "allskywithclear"
warn_allocations_diagnostics: true
log_progress: false
apply_limiter: false
precip_model: "0M"
h_elem: 12
initial_condition: "MoistBaroclinicWave"
t_end: "1mins"
z_elem: 25
dt: "1secs"
dt_save_to_sol: "Inf"
moist: "equil"
