job_id: advective_edmfx_trmm_box
initial_condition: TRMM_LBA
rad: TRMM_LBA
surface_setup: TRMM_LBA
turbconv: advective_edmfx
edmfx_upwinding: first_order
edmfx_entr_model: "ConstantCoefficient"
edmfx_detr_model: "BOverW"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
prognostic_tke: false
moist: equil
apply_limiter: false
precip_model: "0M"
config: box
hyperdiff: "true"
kappa_4: 1e12
x_max: 1e5
y_max: 1e5
z_max: 16400
x_elem: 2
y_elem: 2
z_elem: 82
z_stretch: false
dt: 5secs
t_end: 6hours
dt_save_to_disk: 10mins
FLOAT_TYPE: "Float64"
toml: [toml/advective_edmfx_box.toml]
