dt_save_state_to_disk: "Inf"
dt_save_to_sol: "Inf"
output_default_diagnostics: false
h_elem: 30
z_max: 55000.0
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
moist: equil 
surface_setup: DefaultMoninObukhov 
rad: allskywithclear
insolation: "timevarying"
dt_rad: 1hours
dt_cloud_fraction: 1hours
turbconv: diagnostic_edmfx 
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
cloud_model: diagnostic_edmfx
precip_model: 0M
dt: 90secs
t_end: 1days
toml: [toml/diagnostic_edmfx.toml]
ode_algo: ARS343
