reference_job_id: "les_box"
initial_condition: "DryDensityCurrentProfile"
config: "box"
smagorinsky_lilly: true
c_smag: 0.25
discrete_hydrostatic_balance: true
hyperdiff: "false"
x_max: 51200.0
y_max: 51200.0
z_max: 6400.0
x_elem: 45
y_elem: 45
z_elem: 45
z_stretch: false
dt: "0.25secs"
t_end: "20secs"
prandtl_turbulent_neutral: 0.333
dt_save_state_to_disk: "5secs"
netcdf_interpolation_num_points: [40, 40, 80]
diagnostics:
  - short_name: [wa, ua, va, ta, thetaa, ha]
    period: 5secs 
