dt_save_state_to_disk: "10secs"
initial_condition: "DryDensityCurrentProfile"
x_max: 51200.0
z_elem: 45
dt: "0.1secs"
t_end: "300.0secs"
y_max: 6400.0
y_elem: 15
z_stretch: false
x_elem: 45
ode_algo: "SSP33ShuOsher"
rayleigh_sponge: true
config: "box"
vorticity_hyperdiffusion_coefficient: 0.6
scalar_hyperdiffusion_coefficient: 0.6
z_max: 6400.0
job_id: "box_density_current_test"
smagorinsky_lilly: true
c_smag: 0.2
diagnostics:
  - short_name: thetaa
    period: 10secs
  - short_name: ua
    period: 10secs
  - short_name: wa
    period: 10secs
