dt_save_state_to_disk: "10secs"
initial_condition: "DryDensityCurrentProfile"
x_max: 51200.0
z_elem: 45
dt: "0.1secs"
t_end: "900.0secs"
discrete_hydrostatic_balance: true
y_max: 6400.0
y_elem: 15
z_stretch: false
x_elem: 45
ode_algo: "SSP33ShuOsher"
config: "box"
vorticity_hyperdiffusion_coefficient: 0.05
scalar_hyperdiffusion_coefficient: 0.05
z_max: 6400.0
job_id: "box_density_current_test"
smagorinsky_lilly: true
c_smag: 0.25
diagnostics:
  - short_name: [thetaa, wa, ua, ta, va, hfes, rhoa, rv, ha]
    period: 30secs
