dt_save_state_to_disk: "30secs"
initial_condition: "DryDensityCurrentProfile"
x_max: 51200.0
z_elem: 45
dt: "0.25secs"
t_end: "900.0secs"
y_max: 6400.0
y_elem: 15
z_stretch: false
x_elem: 45
rayleigh_sponge: true
config: "box"
vorticity_hyperdiffusion_coefficient: 0.0
scalar_hyperdiffusion_coefficient: 0.0
z_max: 6400.0
job_id: "box_density_current_test"
smagorinsky_lilly: true
c_smag: 0.2
output_default_diagnostics: false
diagnostics:
  - short_name: thetaa
    period: 30secs
  - short_name: ua
    period: 30secs
  - short_name: wa
    period: 30secs
