job_id: diagnostic_edmfx_trmm_box
initial_condition: TRMM_LBA
rad: TRMM_LBA
surface_setup: TRMM_LBA
turbconv: diagnostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
apply_limiter: false
precip_model: "0M"
override_Ï„_precip: false
config: box
hyperdiff: "true"
kappa_4_vorticity: 1e21
kappa_4_tracer: 1e21
x_max: 1e8
y_max: 1e8
x_elem: 2
y_elem: 2
z_elem: 82
z_max: 16400
z_stretch: false
dt: 200secs
t_end: 6hours
dt_save_to_disk: 10mins
FLOAT_TYPE: "Float64"
toml: [toml/diagnostic_edmfx_trmm_box.toml]
