surface_setup: DefaultMoninObukhov
rad: clearsky
turbconv: diagnostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
cloud_model: "quadrature_sgs"
precip_model: 1M
dt: 100secs
t_end: 12hours
dt_save_state_to_disk: 12hours
reproducibility_test: true
toml: [toml/diagnostic_edmfx.toml]
ode_algo: ARS343
