surface_setup: DefaultMoninObukhov
rad: clearsky
turbconv: diagnostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: false
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
cloud_model: diagnostic_edmfx
precip_model: 0M
override_Ï„_precip: false
dt: 50secs
t_end: 12hours
dt_save_state_to_disk: 12hours
regression_test: true
toml: [toml/diagnostic_edmfx_0M.toml]
restart_file: "output/diagnostic_edmfx_aquaplanet/output_0001/day0.24600.hdf5"
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr]
    period: 100secs
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke, lmix]
    period: 100secs
