job_id: "diagnostic_edmfx_bomex_box"
initial_condition: "Bomex" 
subsidence: "Bomex" 
edmf_coriolis: "Bomex" 
ls_adv: "Bomex" 
surface_setup: "Bomex"
turbconv: "diagnostic_edmfx" 
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: "first_order" 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: "equil"
config: "box" 
hyperdiff: "true" 
kappa_4_vorticity: 1e21
kappa_4_tracer: 1e21
x_max: 1e8 
y_max: 1e8 
x_elem: 2 
y_elem: 2 
z_elem: 60 
z_max: 3e3 
z_stretch: false
dt: "100secs" 
t_end: "6hours" 
dt_save_to_disk: "10mins"
toml: [toml/diagnostic_edmfx_box.toml]
diagnostics:
  - short_name: ts
    period: 10mins
  - short_name: ta
    period: 10mins
  - short_name: thetaa
    period: 10mins
  - short_name: ha
    period: 10mins
  - short_name: pfull
    period: 10mins
  - short_name: rhoa
    period: 10mins
  - short_name: ua
    period: 10mins
  - short_name: va
    period: 10mins
  - short_name: wa
    period: 10mins
  - short_name: hur
    period: 10mins
  - short_name: hus
    period: 10mins
  - short_name: clw
    period: 10mins
  - short_name: cli
    period: 10mins
  - short_name: hussfc
    period: 10mins
  - short_name: evspsbl
    period: 10mins
  - short_name: arup
    period: 10mins
  - short_name: waup
    period: 10mins
  - short_name: taup
    period: 10mins
  - short_name: thetaaup
    period: 10mins
  - short_name: haup
    period: 10mins
  - short_name: husup
    period: 10mins
  - short_name: hurup
    period: 10mins
  - short_name: clwup
    period: 10mins
  - short_name: cliup
    period: 10mins
  - short_name: waen
    period: 10mins
  - short_name: tke
    period: 10mins
  - short_name: lmix
    period: 10mins
