job_id: "diagnostic_edmfx_aquaplanet" 
vert_diff: "true" 
surface_setup: "DefaultExchangeCoefficients" 
rad: "gray" 
turbconv: "diagnostic_edmfx" 
edmfx_entr_detr: true 
moist: "equil" 
precip_model: "0M" 
dt: "400secs" 
t_end: "1days" 
dt_save_to_disk: "12hours"
