job_id: "diagnostic_edmfx_bomex_box"
initial_condition: "Bomex" 
subsidence: "Bomex" 
edmf_coriolis: "Bomex" 
ls_adv: "Bomex" 
surface_setup: "Bomex"
turbconv: "diagnostic_edmfx" 
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: "first_order" 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: "equil"
config: "box" 
hyperdiff: "true" 
x_max: 1e8 
y_max: 1e8 
x_elem: 2 
y_elem: 2 
z_elem: 60 
z_max: 3e3 
z_stretch: false
dt: "100secs" 
t_end: "6hours" 
dt_save_state_to_disk: "10mins"
toml: [toml/diagnostic_edmfx_box.toml]
