job_id: edmfx_dycoms_rf01_box
initial_condition: DYCOMS_RF01
subsidence: DYCOMS
edmf_coriolis: DYCOMS_RF01
rad: DYCOMS_RF01
surface_setup: DYCOMS_RF01
turbconv: edmfx
edmfx_upwinding: first_order
edmfx_entr_model: "ConstantCoefficient"
edmfx_detr_model: "ConstantCoefficient"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: false
prognostic_tke: false
moist: equil
config: box
hyperdiff: "true"
kappa_4: 1e12
x_max: 1e5
y_max: 1e5
z_max: 1500
x_elem: 2
y_elem: 2
z_elem: 30
z_stretch: false
dt: 1secs
t_end: 2400secs
dt_save_to_disk: 2secs
toml: [toml/edmfx_box.toml]
