job_id: "edmfx_rico_box"
initial_condition: "Rico"
subsidence: "Rico"
ls_adv: "Rico"
surface_setup: "Rico"
turbconv: "edmfx"
edmfx_upwinding: first_order
edmfx_entr_model: "ConstantCoefficient"
edmfx_detr_model: "ConstantCoefficient"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: false
prognostic_tke: false
moist: "equil"
#precip_model: "0M"
config: "box"
hyperdiff: "true"
kappa_4: 1e12
x_max: 1e5
y_max: 1e5
z_max: 4e3
x_elem: 2
y_elem: 2
z_elem: 100
z_stretch: false
perturb_initstate: false
dt: "1secs"
t_end: "10800secs"
dt_save_to_disk: "10secs"
toml: [toml/edmfx_box.toml]
