job_id: "edmfx_gabls_box"
initial_condition: GABLS
edmf_coriolis: GABLS
surface_setup: GABLS
turbconv: "edmfx"
edmfx_upwinding: "first_order"
edmfx_entr_model: "ConstantCoefficient"
edmfx_detr_model: "ConstantCoefficient"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: false
prognostic_tke: false
moist: "equil"
config: "box"
hyperdiff: "true"
kappa_4: 1e12
x_max: 1e5
y_max: 1e5
z_max: 400
x_elem: 2
y_elem: 2
z_elem: 8
z_stretch: false
dt: "5secs"
t_end: "9hours"
dt_save_to_disk: "10mins"
perturb_initstate: false
FLOAT_TYPE: "Float64"
toml: [toml/edmfx_box.toml]
