config: "box"
FLOAT_TYPE: "Float32"
initial_condition: "ConstantBuoyancyFrequencyProfile"
topography: "Cosine2D"
x_max: 100e3
y_max: 100e3
z_max: 21e3
x_elem: 15
y_elem: 2
z_elem: 50
z_stretch: false
dt: "10secs"
t_end: "5days"
rayleigh_sponge: true
toml: [toml/analytic_topography_test.toml]
check_steady_state: true
output_default_diagnostics: false
diagnostics:
  - short_name: [orog, ua, wa, uapredicted, wapredicted, uaerror, waerror]
    period: 1hours
