dt_save_state_to_disk: "3hours"
dt_save_to_sol: "Inf"
surface_setup: DefaultMoninObukhov
rad: clearsky
turbconv: diagnostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
precip_model: 0M
dt: 100secs
t_end: 6hours
toml: [toml/diagnostic_edmfx_0M.toml]
ode_algo: ARS343
