surface_setup: DefaultMoninObukhov 
rad: clearsky
turbconv: prognostic_edmfx 
prognostic_tke: true
implicit_diffusion: true
implicit_sgs_advection: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 3
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil 
precip_model: 0M
dt: 10secs 
t_end: 1hours 
dt_save_to_disk: 600secs
toml: [toml/prognostic_edmfx.toml]
output_default_diagnostics: false
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hfes, hur, hus, cl, clw, cli, evspsbl, rsd, rsu, rld, rlu]
    reduction_time: average
    period: 1hours
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke, lmix]
    reduction_time: average
    period: 1hours
ode_algo: ARS343
