# Dycoms RF01 config
initial_condition: DYCOMS_RF01
edmf_coriolis: DYCOMS_RF01
subsidence: DYCOMS
rad: DYCOMS
surface_setup: DYCOMS_RF01
config: box
# microphysics
moist: "equil"
precip_model: "1M"
# diffusion
hyperdiff: false
smagorinsky_lilly: true
c_smag: 0.15
# time and spatial discretization, ICs, BCs
ode_algo: "SSPKnoth"
x_max: 500.0
y_max: 500.0
z_max: 1.5e3
x_elem: 4
y_elem: 4
z_elem: 300
z_stretch: false
tracer_upwinding: third_order
dt_cloud_fraction: "10mins"
dt: "0.05secs"
t_end: "4hours"
rayleigh_sponge: true
toml: [toml/les_dycoms.toml]  # sponge height
restart_file: "/groups/esm/hervik/climaatmos-les-artifacts/les_dycoms_day0.0.hdf5"
# diagnostics
dt_save_state_to_disk: "30mins"
output_default_diagnostics: false
netcdf_interpolation_num_points: [30,30,75]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, hfes]
    period: 10mins
