job_id: les_rico_box
initial_condition: Rico
subsidence: Rico
ls_adv: Rico
surface_setup: Rico
implicit_diffusion: false
approximate_linear_solve_iters: 2
moist: equil
apply_limiter: false
precip_model: "1M"
config: box
hyperdiff: "false"
vorticity_hyperdiffusion_coefficient: 0.2
scalar_hyperdiffusion_coefficient: 0.2
dt_cloud_fraction: "10mins"
ode_algo: "SSPKnoth"
smagorinsky_lilly: true
tracer_upwinding: "third_order"
energy_upwinding: "third_order"
c_smag: 0.20
x_max: 4e3
y_max: 4e3
x_elem: 10
y_elem: 10
z_elem: 150
z_max: 6e3
z_stretch: false
dt: "0.2secs"
t_end: 4hours
restart_file: "/home/edejong/ClimaAtmos.jl/restart/rico/day0.0.hdf5"
toml: [toml/rico_box.toml]
dt_save_state_to_disk: 30mins
netcdf_interpolation_num_points: [30, 30, 150]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, hfes, pr]
    period: 10mins
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, hfes, pr]
    reduction_time: average
    period: 60mins
