job_id: les_rico_box
initial_condition: Rico
subsidence: Rico
ls_adv: Rico
surface_setup: Rico
implicit_diffusion: false
approximate_linear_solve_iters: 2
moist: equil
apply_limiter: false
precip_model: "1M"
config: box
hyperdiff: "true"
vorticity_hyperdiffusion_coefficient: 0.2
scalar_hyperdiffusion_coefficient: 0.2
dt_cloud_fraction: "10mins"
ode_algo: "SSPKnoth"
smagorinsky_lilly: true
c_smag: 0.20
x_max: 4e3
y_max: 4e3
x_elem: 10
y_elem: 10
z_elem: 150
z_max: 6e3
z_stretch: false
dt: "0.2secs"
t_end: 8hours
#restart_file: "/home/asridhar/Codes/ClimaAtmos.jl/restart/rico/Micro1M_day0.0_Prod.hdf5"
restart_file: "/home/asridhar/Codes/ClimaAtmos.jl/restart/rico/day0.3783.hdf5"
toml: [toml/rico_box.toml]
dt_save_state_to_disk: 10mins
netcdf_interpolation_num_points: [20, 20, 100]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl]
    period: 10mins
  - short_name: [husra, hussn]
    period: 10mins
