device: "CPUSingleThreaded"
job_id: "les_bomex_box"
initial_condition: "Bomex" 
edmf_coriolis: "Bomex"
subsidence: "Bomex" 
ls_adv: "Bomex" 
surface_setup: "Bomex"
moist: "equil"
config: "box" 
hyperdiff: "true" 
implicit_diffusion: false
ode_algo: "SSP33ShuOsher"
precip_model: "1M"
vorticity_hyperdiffusion_coefficient: 0
scalar_hyperdiffusion_coefficient: 0
smagorinsky_lilly: true
c_smag: 0.20
x_max: 2e3
y_max: 2e3 
z_max: 2e3 
x_elem: 7
y_elem: 7
z_elem: 20 
z_stretch: false
dt: "0.05secs" 
t_end: "10secs" 
dt_save_state_to_disk: "10mins"
restart_file: "restart/bomex/day0.0.hdf5"
netcdf_interpolation_num_points: [40, 40, 80]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl]
    period: 5secs
