# GABLS config
edmf_coriolis: GABLS
initial_condition: GABLS
surface_setup: GABLS
config: "box"
# microphysics
moist: "equil"
precip_model: "1M"
# diffusion
implicit_diffusion: false
hyperdiff: false
# time and spatial discretization, ICs, BCs
ode_algo: "SSPKnoth"
x_max: 1e3
y_max: 1e3
z_max: 500
x_elem: 5
y_elem: 5
z_elem: 10
z_stretch: false
dt: "0.10secs"
t_end: "100secs"
perturb_initstate: true
# diagnostics
dt_save_state_to_disk: "30mins"
netcdf_output_at_levels: true
netcdf_interpolation_num_points: [20, 20, 20]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl]
    period: 10secs
