dt_save_state_to_disk: "3600secs"
rayleigh_sponge: true
initial_condition: "ScharProfile"
x_max: 120000.0
z_elem: 45
dt: "0.5secs"
t_end: "14400.0secs"
z_stretch: false
x_elem: 100
ode_algo: "SSP33ShuOsher"
config: "plane"
vorticity_hyperdiffusion_coefficient: 0.5
scalar_hyperdiffusion_coefficient: 0.5
z_max: 25000.0
topography: "Schar"
toml: [toml/plane_schar_mountain_test_uniform.toml]
diagnostics:
  - short_name: wa
    period: 4hours
