config: "plane"
FLOAT_TYPE: "Float64"
initial_condition: "ConstantBuoyancyFrequencyProfile"
topography: "Agnesi"
x_max: 100e3
z_max: 21e3
x_elem: 100
z_elem: 100
dz_bottom: 10
dz_top: 1000
dt: "0.7secs"
t_end: "2.5days"
rayleigh_sponge: true
toml: [toml/analytic_topography_test.toml]
check_steady_state: true
output_default_diagnostics: false
diagnostics:
  - short_name: [orog, ua, wa, uapredicted, wapredicted, uaerror, waerror]
    period: 1hours
