config: "plane"
FLOAT_TYPE: "Float64"
initial_condition: "ConstantBuoyancyFrequencyProfile"
topography: "Cosine2D"
x_max: 100e3
z_max: 21e3
x_elem: 15
z_elem: 50
z_stretch: false
nh_poly: 2
dt: "10secs"
t_end: "40days"
rayleigh_sponge: true
toml: [toml/analytic_topography_test.toml]
check_steady_state: true
output_default_diagnostics: false
diagnostics:
  - short_name: [orog, ua, wa, uapredicted, wapredicted, uaerror, waerror]
    period: 1hours
