dt_save_state_to_disk: "3600secs"
rayleigh_sponge: true
initial_condition: "AgnesiHProfile"
x_max: 240000.0
z_elem: 90
dt: "1.5secs"
t_end: "14400.0secs"
z_stretch: false
x_elem: 80
config: "plane"
hyperdiff: false
z_max: 25000.0
topography: "Agnesi"
toml: [toml/plane_agnesi_mountain_test_uniform.toml]
diagnostics:
  - short_name: wa
    period: 4hours
