job_id: "prognostic_edmfx_rico_column"
initial_condition: "Rico"
subsidence: "Rico"
ls_adv: "Rico"
surface_setup: "Rico"
turbconv: "prognostic_edmfx"
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_velocity_relaxation: true
prognostic_tke: true
moist: "equil"
precip_model: "0M"
config: "column"
z_max: 4e3
x_elem: 2
y_elem: 2
z_elem: 100
z_stretch: false
perturb_initstate: false
dt: "5secs"
t_end: "6hours"
dt_save_state_to_disk: "10mins"
toml: [toml/prognostic_edmfx_box.toml]
netcdf_output_at_levels: true
netcdf_interpolation_num_points: [8, 8, 100]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl]
    period: 10mins
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, taen, thetaaen, haen, husen, huren, clwen, clien, tke, lmix]
    period: 10mins
