job_id: "prognostic_edmfx_gabls_tke_column"
initial_condition: GABLS
edmf_coriolis: GABLS
surface_setup: GABLS
turbconv: "prognostic_edmfx"
edmfx_upwinding: "first_order"
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
prognostic_tke: true
moist: "equil"
config: "column"
hyperdiff: "false"
z_max: 400
x_elem: 2
y_elem: 2
z_elem: 8
z_stretch: false
dt: "5secs"
t_end: "9hours"
dt_save_to_disk: "10mins"
perturb_initstate: false
toml: [toml/prognostic_edmfx_box.toml]
