job_id: "prognostic_edmfx_adv_test_box"
initial_condition: "MoistAdiabaticProfileEDMFX"
advection_test: true
turbconv: "prognostic_edmfx"
ode_algo: "SSP33ShuOsher"
edmfx_upwinding: "first_order"
config: "box"
moist: "equil"
hyperdiff: "true"
x_max: 1e8
y_max: 1e8
z_max: 5.5e4
x_elem: 2
y_elem: 2
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
dt: "10secs"
t_end: "3600secs"
dt_save_state_to_disk: "100secs"
FLOAT_TYPE: "Float64"
toml: [toml/prognostic_edmfx_box_advection.toml]
