surface_setup: DefaultMoninObukhov 
rad: clearsky
turbconv: prognostic_edmfx 
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil 
precip_model: 0M
dt: 10secs 
t_end: 1hours 
dt_save_state_to_disk: 600secs
toml: [toml/prognostic_edmfx.toml]
output_default_diagnostics: false
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl]
    reduction_time: average
    period: 1hours
  - short_name: [arup, waup, taup, thetaaup, haup, rhoaup, husup, hurup, clwup, cliup, waen, taen, thetaaen, haen, husen, huren, clwen, clien, tke, lmix]
    reduction_time: average
    period: 1hours
  - short_name: [entr, detr, lmix, bgrad, strain, edt, evu]
    reduction_time: average
    period: 1hours
