job_id: prognostic_edmfx_dycoms_rf01_box
initial_condition: DYCOMS_RF01
subsidence: DYCOMS
edmf_coriolis: DYCOMS_RF01
rad: DYCOMS_RF01
surface_setup: DYCOMS_RF01
turbconv: prognostic_edmfx
edmfx_upwinding: first_order
edmfx_sgsflux_upwinding: first_order
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
prognostic_tke: true
moist: equil
config: box
hyperdiff: "true"
x_max: 1e8
y_max: 1e8
z_max: 1500
x_elem: 2
y_elem: 2
z_elem: 30
z_stretch: false
dt: 10secs
t_end: 4hours
dt_save_state_to_disk: 10mins
toml: [toml/prognostic_edmfx_dycoms_rf01_box.toml]
