config: "column"
initial_condition: "PrecipitatingColumn"
surface_setup: "DefaultMoninObukhov"
dz_bottom: 50.0
z_elem: 100
z_max: 10000.0
dt: "10secs"
t_end: "1500secs"
dt_save_to_disk: "500secs"
moist: "equil"
precip_model: "1M"
vert_diff: "true"
hyperdiff: "false"
rayleigh_sponge: true
regression_test: false
job_id: "single_column_precipitation_test"
diagnostics:
  - short_name: hus
    period: 500secs
  - short_name: clw
    period: 500secs
  - short_name: cli
    period: 500secs
  - short_name: husra
    period: 500secs
  - short_name: hussn
    period: 500secs
  - short_name: ta
    period: 500secs
  - short_name: wa
    period: 500secs
