dt_save_to_disk: "100days"
initial_condition: "IsothermalProfile"
hyperdiff: "false"
z_elem: 70
dt: "3hours"
t_end: "654days"
dz_top: 10000.0
dz_bottom: 100.0
config: "column"
z_max: 70000.0
dt_save_to_sol: "30hours"
job_id: "single_column_radiative_equilibrium_gray"
rad: "gray"
