z_max: 70000.0
z_elem: 99
dz_bottom: 30.0
rad: "clearsky"
idealized_h2o: true
hyperdiff: false
config: "column"
initial_condition: "IsothermalProfile"
t_end: "654days"
dt: "3hours"
dt_rad: "3hours"
dt_save_to_sol: "30hours"
dt_save_state_to_disk: "100days"
prognostic_surface: true
surface_setup: DefaultExchangeCoefficients
toml: [toml/single_column_radiative_equilibrium_clearsky_prognostic_surface_temp.toml]
