dt_save_state_to_disk: "100days"
initial_condition: "IsothermalProfile"
hyperdiff: false
z_elem: 70
dt: "3hours"
idealized_h2o: true
t_end: "654days"
dz_top: 10000.0
idealized_clouds: true
dz_bottom: 100.0
config: "column"
insolation: "timevarying"
z_max: 70000.0
dt_save_to_sol: "30hours"
rad: "allskywithclear"
diagnostics:
  - short_name: rhoa
    reduction_time: average
    period: 1months
