dt_save_state_to_disk: "100days"
initial_condition: "IsothermalProfile"
hyperdiff: false
z_elem: 63
dt: "3hours"
dt_rad: "3hours"
idealized_h2o: true
t_end: "654days"
idealized_clouds: true
dz_bottom: 30.0
config: "column"
insolation: "timevarying"
z_max: 70000.0
dt_save_to_sol: "30hours"
rad: "allskywithclear"
diagnostics:
  - short_name: rhoa
    reduction_time: average
    period: 1months
