z_max: 70000.0
z_elem: 99
dz_bottom: 30.0
dt_save_state_to_disk: "100days"
initial_condition: "IsothermalProfile"
hyperdiff: false
dt: "3hours"
dt_rad: "3hours"
idealized_h2o: true
t_end: "654days"
config: "column"
dt_save_to_sol: "30hours"
rad: "clearsky"
