dt_save_state_to_disk: "100days"
initial_condition: "IsothermalProfile"
hyperdiff: "false"
z_elem: 70
dt: "3hours"
t_end: "654days"
dz_top: 10000.0
dz_bottom: 100.0
config: "column"
z_max: 70000.0
dt_save_to_sol: "30hours"
rad: "gray"
# [2, 2, 80] instead of [1, 1, 80] because Julia ranges are inclusive of the
# extrema. Given that our columns are 3D, we cannot map the horizontal dimension
# with just one point.
netcdf_interpolation_num_points: [2, 2, 80]
