dz_bottom: 30.0
dt_save_to_disk: "5days"
initial_condition: "IsothermalProfile"
config: "column"
hyperdiff: "false"
z_elem: 45
dt: "3hours"
FLOAT_TYPE: "Float64"
job_id: "single_column_hydrostatic_balance_ft64"
dt_save_to_sol: "3hours"
