config: "column"
initial_condition: "PrecipitatingColumnNM"
surface_setup: "DefaultMoninObukhov"
z_elem: 5
z_max: 250.0
z_stretch: false
dt: "10secs"
t_end: "10secs"
dt_save_state_to_disk: "10secs"
dt_cloud_fraction: "10secs"
moist: "nonequil"
precip_model: "NM"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
regression_test: false
check_precipitation: true
job_id: "single_column_precipitation_test"
toml: [toml/single_column_precipitation_test.toml]
diagnostics:
  - short_name: [hus, clw, cli, husra, hussn, ta, wa]
    period: 10secs
