config: "column"
initial_condition: "PrecipitatingColumn"
surface_setup: "DefaultMoninObukhov"
z_elem: 200
z_max: 10000.0
z_stretch: false
dt: "10secs"
t_end: "1500secs"
dt_save_state_to_disk: "500secs"
dt_cloud_fraction: "60secs"
moist: "nonequil"
precip_model: "1M"
precip_upwinding: "first_order"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
regression_test: false
check_precipitation: true
job_id: "single_column_precipitation_test"
toml: [toml/single_column_precipitation_test.toml]
diagnostics:
  - short_name: [hus, clw, cli, husra, hussn, ta, wa]
    period: 500secs
