z_elem: 25
z_max: 55000.0
dz_bottom: 300.0
dt: "400secs"
t_end: "1days"
dt_save_state_to_disk: "24hours"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
moist: "equil"
precip_model: "1M"
rad: "allskywithclear"
aerosol_radiation: true
insolation: "timevarying"
rayleigh_sponge: true
non_orographic_gravity_wave: true
orographic_gravity_wave: "gfdl_restart"
surface_setup: "DefaultMoninObukhov"
prescribe_ozone: true
prescribed_aerosols: ["CB1", "CB2", "SO4"]
toml: [toml/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.toml]
diagnostics:
  - short_name: [edt, evu, mmrso4, mmrbcpo, mmrbcpi, o3]
    reduction_time: average
    period: "1days"
