dt_save_state_to_disk: "4days"
rayleigh_sponge: true
dt: "450secs"
z_elem: 25
t_end: "4days"
dz_bottom: 300.0
vert_diff: true
forcing: "held_suarez"
z_max: 55000.0
precip_model: "0M"
reproducibility_test: true
viscous_sponge: true
moist: "equil"
toml: [toml/sphere_held_suarez_rhoe_equilmoist_hightop_sponge.toml]
