dt_save_state_to_disk: "2days"
initial_condition: "MoistBaroclinicWave"
topography: "Hughes2023"
topo_smoothing: false
implicit_diffusion: true
approximate_linear_solve_iters: 2
moist: equil
dt: "200secs"
t_end: "10days"
vert_diff: "FriersonDiffusion"
diagnostics:
  - short_name: [pfull, ua, wa, va, rv, pr, cli, hus, ke]
    period: 1days
