dt_save_to_disk: "30secs"
initial_condition: "MoistBaroclinicWaveWithEDMF"
dt: "1secs"
edmfx_entr_model: "ConstantCoefficient" 
edmfx_detr_model: "BOverW" 
edmfx_nh_pressure: true
t_end: "6mins"
turbconv: "edmfx"
ode_algo: "SSP33ShuOsher"
precip_model: "0M"
reference_job_id: "sphere_baroclinic_wave_rhoe_equilmoist"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
job_id: "sphere_baroclinic_wave_rhoe_equilmoist_edmfx"
moist: "equil"
