rad: "allskywithclear"
dt_save_state_to_disk: "1days"
rayleigh_sponge: true
orographic_gravity_wave: "raw_topo"
z_elem: 25
dt: "400secs"
surface_setup: "DefaultMoninObukhov"
t_end: "15hours"
non_orographic_gravity_wave: true
dz_bottom: 300.0
vert_diff: true
insolation: "timevarying"
z_max: 55000.0
precip_model: "0M"
cloud_model: "grid_scale"
surface_temperature: "ZonallyAsymmetric"
moist: "equil"
albedo_model: "RegressionFunctionAlbedo"
regression_test: true
toml: [toml/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric.toml]
