dt_save_to_disk: "2days"
rayleigh_sponge: true
topo_smoothing: true
dt: "200secs"
t_end: "2days"
vert_diff: "true"
use_reference_state: false
forcing: "held_suarez"
precip_model: "0M"
topography: "DCMIP200"
job_id: "sphere_held_suarez_rhoe_equilmoist_topography_dcmip"
moist: "equil"
netcdf_interpolate_z_over_msl: true
diagnostics:
  - short_name: cl
    period: 3hours
  - short_name: cli
    period: 3hours
  - short_name: clw
    period: 3hours
  - short_name: ta
    period: 3hours
  - short_name: hus
    period: 3hours
  - short_name: hur
    period: 3hours
  - short_name: lmix
    period: 3hours
