dt_save_state_to_disk: "8days"
use_reference_state: false
t_end: "8days"
discrete_hydrostatic_balance: true
hyperdiff: "false"
perturb_initstate: false
FLOAT_TYPE: "Float64"
dt_save_to_sol: "600secs"
