rad: "allskywithclear"
dt_save_state_to_disk: "1days"
rayleigh_sponge: true
z_elem: 25
dt: "400secs"
surface_setup: "DefaultMoninObukhov"
t_end: "15hours"
dz_bottom: 300.0
vert_diff: "true"
idealized_insolation: false
z_max: 45000.0
precip_model: "0M"
cloud_model: "grid_scale"
surface_temperature: "ZonallyAsymmetric"
job_id: "sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric2"
moist: "equil"
toml: [toml/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric.toml]
netcdf_interpolate_z_over_msl: true
