z_elem: 25
z_max: 55000.0
dz_bottom: 300.0
dt: "400secs"
t_end: "18hours"
dt_save_state_to_disk: "18hours"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
moist: "nonequil"
precip_model: "nothing"
rad: "allskywithclear"
idealized_insolation: false
rayleigh_sponge: true
surface_setup: "DefaultMoninObukhov"
toml: [toml/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.toml]
