dt_save_state_to_disk: "5days"
initial_condition: "MoistHughes2023BaroclinicWave"
topography: "Hughes2023"
topo_smoothing: false
dt: "200secs"
moist: "equil"
t_end: "10days"
job_id: "sphere_baroclinic_wave_rhoe_hughes2023"
diagnostics:
  - short_name: [pfull, wa, va, rv, ke]
    period: 1days
