rad: "allskywithclear"
dt_save_to_disk: "1days"
rayleigh_sponge: true
orographic_gravity_wave: "raw_topo"
z_elem: 25
dt: "400secs"
surface_setup: "DefaultMoninObukhov"
t_end: "15hours"
non_orographic_gravity_wave: true
dz_bottom: 300.0
vert_diff: "true"
idealized_insolation: false
z_max: 45000.0
precip_model: "0M"
regression_test: true
surface_temperature: "ZonallyAsymmetric"
job_id: "sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric"
moist: "equil"
toml: [toml/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric.toml]
netcdf_interpolate_z_over_msl: true
diagnostics:
  - short_name: ua
    reduction_time: average
    period: 12hours
  - short_name: ta
    reduction_time: average
    period: 12hours
  - short_name: hus
    reduction_time: average
    period: 12hours
  - short_name: hfes
    reduction_time: average
    period: 12hours
  - short_name: evspsbl
    reduction_time: average
    period: 12hours
  - short_name: rsd
    reduction_time: average
    period: 12hours
  - short_name: rsu
    reduction_time: average
    period: 12hours
  - short_name: rld
    reduction_time: average
    period: 12hours
  - short_name: rlu
    reduction_time: average
    period: 12hours
