z_elem: 25
z_max: 45000.0
dz_bottom: 300.0
dt: "400secs"
t_end: "24hours"
dt_save_state_to_disk: "24hours"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
moist: "equil"
precip_model: "1M"
precip_upwinding: "first_order"
rad: "allskywithclear"
idealized_insolation: false
rayleigh_sponge: true
non_orographic_gravity_wave: true
orographic_gravity_wave: "gfdl_restart"
surface_setup: "DefaultMoninObukhov"
job_id: "sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res"
toml: [toml/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.toml]
