topography: "DCMIP200"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "DryBaroclinicWave"
t_end: "6days"
use_reference_state: false
dt: "200secs"
job_id: "sphere_baroclinic_wave_rhoe_topography_dcmip_rs"
diagnostics:
  - short_name: [pfull, ua, wa, va, rv, ta, ke]
    period: 1days
  - short_name: [pfull, ua, wa, va, rv, ta, ke]
    period: 1days
    writer: h5
