dt: 200secs 
t_end: 800days 
ode_algo: ARS343
dt_save_to_disk: 30days 
moist: equil
forcing: held_suarez 
precip_model: 0M 
diagnostics:
  - reduction_time: average
    short_name: thetaa
    period: 6hours
    writer: nc
  - reduction_time: average
    short_name: thetaa
    period: 30days
    writer: nc
  - reduction_time: average
    short_name: ts
    period: 6hours
    writer: nc
  - reduction_time: average
    short_name: ts
    period: 30days
    writer: nc
  - reduction_time: average
    short_name: ta
    period: 6hours
    writer: nc
  - reduction_time: average
    short_name: ta
    period: 30days
    writer: nc

job_id: sphere_held_suarez_rhoe_equilmoist_6
output_dir: sphere_held_suarez_rhoe_equilmoist_6
toml: [toml/sphere_held_suarez_rhoe_equilmoist_6.toml]