precip_model: "0M"
vert_diff: "true"
z_elem: 20
dz_bottom: 100
dt_save_state_to_disk: "6hours"
initial_condition: "MoistBaroclinicWave"
dt: "20secs"
t_end: "6hours"
job_id: "sphere_baroclinic_wave_rhoe_equilmoist_expvdiff"
moist: "equil"
toml: [toml/sphere_baroclinic_wave_rhoe_equilmoist_expvdiff.toml]
diagnostics:
  - short_name: pfull
    period: 6hours
  - short_name: rv
    period: 6hours
  - short_name: ua
    period: 6hours
  - short_name: va
    period: 6hours
  - short_name: wa
    period: 6hours
  - short_name: ta
    period: 6hours
  - short_name: hus
    period: 6hours
