h_elem: 120
z_elem: 43
dz_bottom: 30.0
dt: "40secs"
t_end: "10days"
ode_algo: ARS343
topography: "Hughes2023"
topo_smoothing: false 
perturb_initstate: false
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "0M"
dt_save_state_to_disk: "10days"
netcdf_interpolation_num_points: [1440, 720, 43]
vert_diff: DecayWithHeightDiffusion
implicit_diffusion: true
approximate_linear_solve_iters: 2
rayleigh_sponge: true
toml: [toml/longrun_baroclinicwave.toml]
output_dir: "/glade/derecho/scratch/asridhar/moist_bw_hughes_he120"
diagnostics:
  - short_name: [pfull, ps, ua, va, ta, ts, wa, rv, ke, hus, clw, cli, pr]
    reduction: inst
    period: 1days
  - short_name: [massa, energya, watera]
    period: 6hours
    writer: dict
