h_elem: 30
z_elem: 43
dz_bottom: 30.0
dt: "180secs"
t_end: "360days"
ode_algo: ARS343
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "0M"
dt_save_state_to_disk: "10days"
FLOAT_TYPE: Float32
toml: [toml/precip.toml]
prognostic_surface: PrognosticSurfaceTemperature
output_dir: "/glade/derecho/scratch/asridhar/moist_bw_ars343_f32_cons"
diagnostics:
  - short_name: [watera, energya, massa, energyo, watero]
    period: 6hours
    writer: dict
