h_elem: 30
z_elem: 43
dz_bottom: 30.0
dt: "90secs"
t_end: "30days"
ode_algo: ARS343
approximate_linear_solve_iters: 2
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "1M"
dt_save_state_to_disk: "10days"
toml: [toml/longrun_baroclinic_wave.toml]
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
