dt_save_state_to_disk: "10days"
initial_condition: "MoistBaroclinicWave"
z_elem: 45
dt: "300secs"
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
precip_model: "0M"
job_id: "longrun_bw_rhoe_equil_highres"
moist: "equil"
diagnostics:
  - short_name: pfull
    period: 1days
  - short_name: wa
    period: 1days
  - short_name: va
    period: 1days
  - short_name: rv
    period: 1days
  - short_name: hus
    period: 1days
