FLOAT_TYPE: "Float32"
dt_save_to_disk: "10days"
dt: "120secs"
t_end: "8hours"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
kappa_4_vorticity: 1.0e16
kappa_4_tracer: 1.0e16
moist: "equil"
precip_model: "1M"
precip_upwinding: "first_order"
surface_setup: "DefaultMoninObukhov"
vert_diff: "true"
rad: "clearsky"
dt_rad: "6hours"
job_id: "longrun_aquaplanet_rhoe_equilmoist_nz63_1M_55km_rs35km_clearsky"
toml: [toml/longrun_aquaplanet_rhoe_equilmoist_nz63_1M_55km_rs35km_clearsky.toml]
output_default_diagnostics: false
diagnostics:
  - short_name: cl
    period: 120secs
  - short_name: cli
    period: 120secs
  - short_name: clw
    period: 120secs
  - short_name: husra
    period: 120secs
  - short_name: hussn
    period: 120secs
  - short_name: ta
    period: 120secs
  - short_name: hus
    period: 120secs
  - short_name: hur
    period: 120secs
  - short_name: lmix
    period: 120secs
