dt_save_state_to_disk: "10days"
dt: "100secs"
rad: "clearsky"
dt_rad: "6hours"
t_end: "200days"
dz_bottom: 30.0
dz_top: 3000.0
h_elem: 16
z_elem: 63
z_max: 55000.0
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
vorticity_hyperdiffusion_coefficient: 3.0
divergence_damping_factor: 1.0
scalar_hyperdiffusion_coefficient: 3.0
smoothing_order: 2
topo_smoothing: true
mesh_warp_type: "SLEVE"
topography: "Earth"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
toml: [toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth_sleve.toml]
