dt: "120secs"
t_end: "50days"  # 300 days
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
moist: "equil"
precip_model: "1M"
precip_upwinding: "first_order"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
rad: "clearsky"
dt_rad: "6hours"
job_id: "longrun_1M"
toml: [toml/longrun_1M.toml]
output_default_diagnostics: false
diagnostics:
  - short_name: [cl, cli, clw, husra, hussn, ta, hus, hur, lmix]
    period: 5days
