dt_save_to_disk: "10days"
dt: "150secs" 
t_end: "300days"
h_elem: 16
z_max: 55000.0
rayleigh_sponge: true
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
vert_diff: "true" 
kappa_4_vorticity: 2e16
kappa_4_tracer: 2e16
surface_setup: "DefaultExchangeCoefficients" 
moist: "equil" 
rad: "gray" 
precip_model: "0M" 
job_id: "longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M" 
toml: [toml/longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M.toml]
