dz_bottom: 30.0
dz_top: 3000.0
dt_save_to_disk: "10days"
t_end: "300days"
h_elem: 16
z_elem: 63
z_max: 55000.0
kappa_4_vorticity: 1.0e16
kappa_4_tracer: 1.0e16
forcing: "held_suarez"
dt: "300secs"
rayleigh_sponge: true
job_id: "longrun_hs_rhoe_dry_nz63_55km_rs35km"
toml: [toml/longrun_hs_rhoe_dry_nz63_55km_rs35km.toml]
