h_elem: 30
z_max: 55000.0
z_elem: 99
dz_bottom: 30.0
dt: "90secs"
t_end: "360days"
deep_atmosphere: true
moist: "equil"
precip_model: "0M"
vert_diff: true
rayleigh_sponge: true
forcing: "held_suarez"
dt_save_state_to_disk: "10days"
toml: [toml/longrun_held_suarez.toml]
