dt_save_state_to_disk: "10days"
initial_condition: "MoistBaroclinicWave"
max_newton_iters_ode: 3
z_elem: 45
dt: "150secs"
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
ode_algo: "SSP333"
precip_model: "0M"
job_id: "longrun_ssp_bw_rhoe_equil_highres"
moist: "equil"
apply_limiter: true
diagnostics:
  - short_name: pfull
    period: 1days
  - short_name: wa
    period: 1days
  - short_name: va
    period: 1days
  - short_name: rv
    period: 1days
  - short_name: hus
    period: 1days
