h_elem: 30
z_elem: 63
z_max: 55000.0
dz_bottom: 30.0
dz_top: 3000.0
dt: "100secs"
t_end: "300days"
moist: "equil"
precip_model: "0M"
vert_diff: "true"
rayleigh_sponge: true
forcing: "held_suarez"
dt_save_state_to_disk: "10days"
toml: [toml/longrun_hs_rhoe_equil_55km_nz63_0M.toml]
