h_elem: 60
z_max: 65000.0
z_elem: 63
dz_bottom: 30.0
rayleigh_sponge: true
viscous_sponge: true
moist: "equil" 
cloud_model: "grid_scale"
dt: "30secs" 
t_end: "10days"
dt_save_state_to_disk: "10days"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov" 
implicit_diffusion: true
approximate_linear_solve_iters: 2
vert_diff: "FriersonDiffusion" 
precip_model: "0M" 
toml: [toml/longrun_aquaplanet.toml]
