h_elem: 30
z_max: 60000.0
z_elem: 63
dz_bottom: 30.0
dt: "90secs"
t_end: "360days"
moist: "equil"
precip_model: "0M"
vert_diff: true
rayleigh_sponge: true
viscous_sponge: true
forcing: "held_suarez"
dt_save_state_to_disk: "10days"
toml: [toml/longrun_held_suarez.toml]
