h_elem: 12
z_max: 55000.0
z_elem: 30
dz_bottom: 100.0
dz_top: 3000.0
moist: "equil"
precip_model: "0M"
override_Ï„_precip: false
rad: "allskywithclear"
dt_rad: "6hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "diagnostic_edmfx"
implicit_diffusion: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 3
prognostic_tke: true
edmfx_upwinding: "first_order"
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
rayleigh_sponge: true
vorticity_hyperdiffusion_coefficient: 1.0
divergence_damping_factor: 4.0
scalar_hyperdiffusion_coefficient: 4.0
smoothing_order: 2
topo_smoothing: true
topography: "Earth"
dt_save_state_to_disk: "10days"
dt: "20secs"
t_end: "2days"
toml: [toml/longrun_aquaplanet_equil_helem12_clearsky_diagedmf_0M.toml]
netcdf_output_at_levels: true
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl]
    period: 1hours
  - short_name: [arup, waup, rhoaup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke]
    period: 1hours
  - short_name: [entr, detr, lmix, bgrad, strain, edt, evu]
    period: 1hours
