dt_save_state_to_disk: "10days"
dt: "100secs"
t_end: "360days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
albedo_model: "RegressionFunctionAlbedo"
prognostic_surface: "PrognosticSurfaceTemperature"
check_conservation: true
bubble: false
toml: [toml/longrun_aquaplanet.toml]
