h_elem: 30
z_elem: 29
dz_bottom: 30.0
dt: "120secs"
t_end: "30days"
ode_algo: IMKG242b
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "0M"
dt_save_state_to_disk: "10days"
output_dir: "/glade/derecho/scratch/asridhar/moist_bw_imkg242b_l30"
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
