h_elem: 30
z_elem: 43
dz_bottom: 30.0
dt: "60secs" # 200
approximate_linear_solve_iters: 3
max_newton_iters_ode: 1
rayleigh_sponge: true
t_end: "120days"
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "0M"
dt_save_state_to_disk: "10days"
toml: [toml/longrun_baroclinic_wave.toml]
diagnostics:
  - short_name: [pfull, wa, va, ua, ta, rhoa, rv, hus, ke, clw, cli]
    period: 1days
