h_elem: 60
z_elem: 43
dz_bottom: 30.0
dt: "30secs"
t_end: "30days"
ode_algo: ARS343
initial_condition: "DryBaroclinicWave"
dt_save_state_to_disk: "10days"
netcdf_interpolation_num_points: [1440, 720, 2]
diagnostics:
  - short_name: [pfull, wa, va, rv, ke]
    period: 1days
