dt_save_state_to_disk: "10days"
dt: "100secs"
rad: "allskywithclear"
dt_rad: "6hours"
t_end: "360days"
dz_bottom: 30.0
dz_top: 3000.0
h_elem: 16
z_elem: 63
z_max: 55000.0
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
topo_smoothing: true
topography: "Earth"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
toml: [toml/longrun_aquaplanet.toml]
