h_elem: 60
z_max: 55000.0
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
moist: "equil" 
precip_model: "0M" 
cloud_model: "grid_scale"
rad: "allskywithclear" 
insolation: "timevarying"
dt_rad: "1hours"
vert_diff: "FriersonDiffusion" 
surface_setup: "DefaultMoninObukhov" 
rayleigh_sponge: true
dt_save_state_to_disk: "10days"
dt: "50secs" 
t_end: "10days"
toml: [toml/longrun_aquaplanet.toml]
