h_elem: 30
z_elem: 43
dz_bottom: 30.0
dt: "200secs"
t_end: "30days"
#ode_algo: IMKG242b
ode_algo: ARS343
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "0M"
dt_save_state_to_disk: "10days"
output_dir: "/glade/derecho/scratch/asridhar/moist_bw_200s_ars343/"
toml: [toml/longrun_baroclinic_wave.toml]
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
