h_elem: 60
z_max: 55000.0
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
kappa_4: 1e14
moist: "equil" 
precip_model: "0M" 
rad: "allskywithclear" 
idealized_insolation: false
dt_rad: "1hours"
vert_diff: "true" 
surface_setup: "DefaultMoninObukhov" 
rayleigh_sponge: true
dt_save_to_disk: "3hours"
dt: "50secs" 
t_end: "1days"
FLOAT_TYPE: "Float32"
job_id: "longrun_aquaplanet_dyamond" 
toml: [toml/longrun_aquaplanet_dyamond.toml]
