dt_save_state_to_disk: "30days"
dt: "40secs"
t_end: "180days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
topography: "Earth"
topo_smoothing: true
vorticity_hyperdiffusion_coefficient: 4.0
scalar_hyperdiffusion_coefficient: 4.0
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultMoninObukhov"
vert_diff: "true"
rad: "clearsky"
dt_rad: "6hours"
job_id: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth"
toml: [toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.toml]
output_default_diagnostics: false
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hfes, hur, hus, hussfc, cl, clw, cli, evspsbl, pr, rsd, rsu, rld, rlu]
    reduction_time: average
    period: 30days
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke, lmix]
    reduction_time: average
    period: 30days
