dt_save_state_to_disk: "10days"
initial_condition: "MoistBaroclinicWave"
z_elem: 45
dt: "200secs"
tracer_upwinding: zalesak
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
energy_upwinding: zalesak
precip_model: "0M"
moist: "equil"
apply_limiter: true
diagnostics:
  - short_name: [pfull, wa, va, rv, hus]
    period: 1days
