h_elem: 60
z_elem: 63
dz_bottom: 30.0
z_max: 30000.0
dt: "30secs"
t_end: "30days"
initial_condition: "MoistBaroclinicWave"
moist: "equil"
tracer_upwinding: tvd_limiter
energy_upwinding: tvd_limiter
precip_model: "0M"
dt_save_state_to_disk: "10days"
netcdf_interpolation_num_points: [360, 180, 64]
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke, ua, ta, thetaa, clw, pr, cli, cl, hur]
    period: 1days
