h_elem: 120
z_elem: 43
dz_bottom: 30.0
dt: "15secs"
t_end: "10days"
ode_algo: ARS343
initial_condition: "DryBaroclinicWave"
dt_save_state_to_disk: "5days"
netcdf_interpolation_num_points: [1440, 720, 43]
diagnostics:
  - short_name: [pfull, ps, ua, va, ta, ts, wa, va, rv, ke]
    reduction: inst
    period: 2days
  - short_name: [massa, energya]
    period: 6hours
    writer: dict
