dz_bottom: 30.0
dt_save_state_to_disk: "10days"
h_elem: 16
initial_condition: "DryBaroclinicWave"
t_end: "100days"
z_elem: 45
dt: "400secs"
job_id: "longrun_bw_rhoe_highres"
output_default_diagnostics: false
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa]
    period: 1days
