h_elem: 240
z_max: 60000.0
z_elem: 63
dz_bottom: 30.0
rayleigh_sponge: true
viscous_sponge: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
topography: "Earth"
start_date: "20160801"
initial_condition: "artifact\"DYAMOND_SUMMER_ICS_p98deg\"/DYAMOND_SUMMER_ICS_p98deg.nc"
moist: "equil"
dt: "10secs"
t_end: "30days"
dt_save_state_to_disk: "10days"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
vert_diff: "DecayWithHeightDiffusion"
precip_model: "0M"
output_dir: "/glade/derecho/scratch/asridhar/dyamond_clima"
toml: [toml/longrun_aquaplanet.toml]
netcdf_interpolation_num_points: [1440, 720, 43]
diagnostics:
  - short_name: [pfull, ps, ua, va, ta, ts, wa, rv, ke, hus, clw, cli, pr]
    reduction: inst
    period: 5days
