h_elem: 12
z_max: 55000.0
z_elem: 35
dz_bottom: 50.0
dz_top: 3000.0
moist: "equil"
precip_model: "0M"
override_Ï„_precip: false
surface_temperature: "ZonallyAsymmetric"
rad: "allskywithclear"
dt_rad: "6hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "prognostic_edmfx"
implicit_sgs_advection: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 3
prognostic_tke: true
edmfx_upwinding: "first_order"
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
rayleigh_sponge: true
dt_save_state_to_disk: "30days"
dt: "20secs"
t_end: "180days"
restart_file: "/net/sampo/data1/zhaoyi/climaatmos/longrun_155/longrun_aquaplanet_equil_helem12_allsky_progedmf_0M_asym/output_active/day120.0.hdf5"
toml: [toml/longrun_aquaplanet_equil_helem12_clearsky_progedmf_0M.toml]
netcdf_output_at_levels: true
diagnostics:
  - short_name: [arup, waup, tke]
    period: 30days
