dt_save_state_to_disk: "10days"
dt: "150secs"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
vert_diff: "true"
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
forcing: "held_suarez"
job_id: "longrun_hs_rhoe_equil_55km_nz63_0M"
toml: [toml/longrun_hs_rhoe_equil_55km_nz63_0M.toml]
