dt_save_state_to_disk: "10days"
initial_condition: "MoistBaroclinicWave"
approximate_linear_solve_iters: 2
z_elem: 45
dt: "150secs"
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
ode_algo: "SSP333"
precip_model: "0M"
job_id: "longrun_ssp_bw_rhoe_equil_highres"
moist: "equil"
apply_limiter: true
diagnostics:
  - short_name: [pfull, wa, va, rv, hus]
    period: 1days
