rad: "clearsky"
dt_save_state_to_disk: "10days"
rayleigh_sponge: true
topo_smoothing: true
z_elem: 45
dt: "100secs"
surface_setup: "DefaultMoninObukhov"
fps: 30
t_end: "300days"
dz_bottom: 30.0
vert_diff: "true"
h_elem: 16
use_reference_state: false
vorticity_hyperdiffusion_coefficient: 4.0
scalar_hyperdiffusion_coefficient: 4.0
FLOAT_TYPE: "Float32"
precip_model: "0M"
topography: "Earth"
dt_save_to_sol: "10days"
job_id: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft32_earth"
moist: "equil"
