h_elem: 16
z_max: 55000.0
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
rayleigh_sponge: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
dt: "120secs"
t_end: "32days"
dt_save_state_to_disk: "10days"
moist: "equil"
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
precip_model: "0M"
toml: [toml/longrun_aquaplanet.toml]
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
diagnostics:
  - short_name: [mmrso4]
    period: "1days"
  - short_name: [mmrso4]
    reduction_time: average
    period: "1months"
