h_elem: 16
z_max: 55000.0
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
kappa_4_vorticity: 1e16
kappa_4_tracer: 1e16
moist: "equil" 
precip_model: "0M" 
override_Ï„_precip: false
rad: "allskywithclear" 
idealized_insolation: false
dt_rad: "1hours"
surface_setup: "DefaultMoninObukhov" 
turbconv: "diagnostic_edmfx" 
prognostic_tke: true
edmfx_upwinding: "first_order" 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
rayleigh_sponge: true
dt_save_to_disk: "3hours"
dt: "5secs" 
t_end: "1days"
FLOAT_TYPE: "Float32"
job_id: "longrun_aquaplanet_amip" 
toml: [toml/longrun_aquaplanet_amip.toml]
