h_elem: 30       # 6
z_elem: 43       # 10
dz_bottom: 30.0  # 300
dt: "100secs"    # 200
#approximate_linear_solve_iters: 3
#max_newton_iters_ode: 1
#rayleigh_sponge: true
t_end: "5days"
initial_condition: "MoistBaroclinicWave"
moist: "nonequil"
precip_model: "1M"
output_dir: "/scratch/ajaruga/dt_100/"
dt_save_state_to_disk: "5days"
diagnostics:
  - short_name: [pfull, wa, va, ua, ta, rhoa, rv, hus, ke, clw, cli, husra, hussn]
    period: 1days
