dz_bottom: 30.0
dt_save_state_to_disk: "10days"
h_elem: 16
initial_condition: "DryBaroclinicWave"
t_end: "100days"
kappa_4_vorticity: 1.0e16
kappa_4_tracer: 1.0e16
z_elem: 45
dt: "400secs"
job_id: "longrun_bw_rhoe_highres"
diagnostics:
  - short_name: pfull
    period: 1days
  - short_name: wa
    period: 1days
  - short_name: va
    period: 1days
  - short_name: rv
    period: 1days
