FLOAT_TYPE: "Float32"
dt_save_to_disk: "10days"
dt: "150secs"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
kappa_4: 2.0e16
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultMoninObukhov"
vert_diff: "true"
rad: "clearsky"
idealized_insolation: false
dt_rad: "1hours"
job_id: "tvinsolation_diff2"
toml: [toml/diff2.toml]

