env:
  JULIA_VERSION: "1.7.2"
  MPICH_VERSION: "4.0.0"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.3"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_time: 04:00:00

timeout_in_minutes: 240

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "ClimaAtmos scaling tests"
    steps:

    - label: ":computer: MPI Held-Suarez scaling test(ρe) - (1) process"
      command:
        - "module load cuda/11.3 nsight-systems/2022.2.1"
        - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=sphere_held_suarez_rhoe/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths:
        - "sphere_held_suarez_rhoe/scaling_data_1_processes.jld2"
        - "sphere_held_suarez_rhoe/report.1.nsys-rep"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
        NPROCS: 1
      agents:
        config: cpu
        queue: central
        slurm_nodes: 1
        slurm_tasks_per_node: 1
        slurm_mem: 64GB

    - label: ":computer: MPI Held-Suarez scaling test(ρe) - (2) processes"
      command:
        - "module load cuda/11.3 nsight-systems/2022.2.1"
        - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=sphere_held_suarez_rhoe/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths:
        - "sphere_held_suarez_rhoe/scaling_data_2_processes.jld2"
        - "sphere_held_suarez_rhoe/report.2.nsys-rep"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
        NPROCS: 2
      agents:
        config: cpu
        queue: central
        slurm_nodes: 1
        slurm_tasks_per_node: 2
        slurm_mem: 64GB

    - label: ":computer: MPI Held-Suarez scaling test(ρe) - (4) processes"
      command:
        - "module load cuda/11.3 nsight-systems/2022.2.1"
        - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=sphere_held_suarez_rhoe/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths:
        - "sphere_held_suarez_rhoe/scaling_data_4_processes.jld2"
        - "sphere_held_suarez_rhoe/report.4.nsys-rep"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
        NPROCS: 4
      agents:
        config: cpu
        queue: central
        slurm_nodes: 1
        slurm_tasks_per_node: 4
        slurm_mem: 64GB

    - label: ":computer: MPI Held-Suarez scaling test(ρe) - (8) processes"
      command:
        - "module load cuda/11.3 nsight-systems/2022.2.1"
        - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=sphere_held_suarez_rhoe/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths:
        - "sphere_held_suarez_rhoe/scaling_data_8_processes.jld2"
        - "sphere_held_suarez_rhoe/report.8.nsys-rep"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
        NPROCS: 8
      agents:
        config: cpu
        queue: central
        slurm_nodes: 1
        slurm_tasks_per_node: 8
        slurm_mem: 64GB

    - label: ":computer: MPI Held-Suarez scaling test(ρe) - (16) processes"
      command:
        - "module load cuda/11.3 nsight-systems/2022.2.1"
        - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=sphere_held_suarez_rhoe/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths:
        - "sphere_held_suarez_rhoe/scaling_data_16_processes.jld2"
        - "sphere_held_suarez_rhoe/report.16.nsys-rep"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
        NPROCS: 16
      agents:
        config: cpu
        queue: central
        slurm_nodes: 1
        slurm_tasks_per_node: 16
        slurm_mem: 128GB

    - label: ":computer: MPI Held-Suarez scaling test(ρe) - (32) processes"
      command:
        - "module load cuda/11.3 nsight-systems/2022.2.1"
        - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=sphere_held_suarez_rhoe/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths:
        - "sphere_held_suarez_rhoe/scaling_data_32_processes.jld2"
        - "sphere_held_suarez_rhoe/report.32.nsys-rep"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
        NPROCS: 32
      agents:
        config: cpu
        queue: central
        slurm_nodes: 1
        slurm_tasks_per_node: 32
        slurm_mem: 256GB


    - label: ":computer: MPI Held-Suarez scaling test(ρe_tot) - (64) processes"
      command: "mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl --job_id sphere_held_suarez_rhoe --forcing held_suarez --enable_threading false --upwinding none --t_end 1hours --dt 100secs --z_elem 40 --h_elem 16 --kappa_4 1e15" 
      artifact_paths: "sphere_held_suarez_rhoe/scaling_data_64_processes.jld2"
      env:
        CLIMACORE_DISTRIBUTED: "MPI"
      agents:
        config: cpu
        queue: central
        slurm_nodes: 2
        slurm_tasks_per_node: 32
        slurm_mem: 256GB

  - wait

  - label: ":computer: scaling plots"
    key: "cpu_scaling_plots"
    command:
      - "julia --color=yes --project=examples examples/hybrid/plot_scaling_results.jl --job_id sphere_held_suarez_rhoe"
    artifact_paths:
      - "sphere_held_suarez_rhoe/Scaling.png"
      - "sphere_held_suarez_rhoe/Scaling_efficiency.png"
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 1
