agents:
  queue: clima
  slurm_mem: 8G
  modules: julia/1.10.0 cuda/julia-pref openmpi/4.1.5-mpitrampoline nsight-systems/2023.4.1

env:
  JULIA_CUDA_MEMORY_POOL: none
  JULIA_MPI_HAS_CUDA: "true"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GPU_BIND: none # https://github.com/open-mpi/ompi/issues/11949#issuecomment-1737712291
  CONFIG_PATH: "config/model_configs"
  GPU_CONFIG_PATH: "config/gpu_configs/"
  PERF_CONFIG_PATH: "config/perf_configs"
  MPI_CONFIG_PATH: "config/mpi_configs"
  CLIMAATMOS_GC_NSTEPS: 10


timeout_in_minutes: 1440

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate examples"
      - julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=examples -e 'using Pkg; Pkg.precompile()'
      - julia --project=examples -e 'using CUDA; CUDA.precompile_runtime()'
      - julia --project=examples -e 'using Pkg; Pkg.status()'

      - echo "--- Download artifacts"
      - julia --project=examples artifacts/download_artifacts.jl

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Timestep sweep"
    steps:

      - label: "Timestep sweep, ARS_nolim_CD, dt=50secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_50secs.yml
        artifact_paths: "dt_ARS_nolim_CD_50secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=60secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_60secs.yml
        artifact_paths: "dt_ARS_nolim_CD_60secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=80secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_80secs.yml
        artifact_paths: "dt_ARS_nolim_CD_80secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=90secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_90secs.yml
        artifact_paths: "dt_ARS_nolim_CD_90secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=100secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_100secs.yml
        artifact_paths: "dt_ARS_nolim_CD_100secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=120secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_120secs.yml
        artifact_paths: "dt_ARS_nolim_CD_120secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=150secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_150secs.yml
        artifact_paths: "dt_ARS_nolim_CD_150secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=160secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_160secs.yml
        artifact_paths: "dt_ARS_nolim_CD_160secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=180secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_180secs.yml
        artifact_paths: "dt_ARS_nolim_CD_180secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=200secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_200secs.yml
        artifact_paths: "dt_ARS_nolim_CD_200secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=240secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_240secs.yml
        artifact_paths: "dt_ARS_nolim_CD_240secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=270secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_270secs.yml
        artifact_paths: "dt_ARS_nolim_CD_270secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "Timestep sweep, ARS_nolim_CD, dt=300secs"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/dt_sweep_configs/ARS_nolim_CD/dt_300secs.yml
        artifact_paths: "dt_ARS_nolim_CD_300secs/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00
