agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_10_08

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  CONFIG_PATH: "config/model_configs"
  GPU_CONFIG_PATH: "config/gpu_configs"
  PERF_CONFIG_PATH: "config/perf_configs"
  MPI_CONFIG_PATH: "config/mpi_configs"

steps:
  - label: "Test on new-central"
    command:
    - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate()'
    - srun nsys profile --trace=nvtx,cuda,mpi --output=report_%q{PMI_RANK} --force-overwrite true julia --project=.buildkite .buildkite/test_cuda_mpi.jl
    - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true
    - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true | grep -E "memcpy (Peer-to-Peer|PtoP)"
    agents:
      queue: new-central
      slurm_ntasks: 2
      slurm_gpus_per_task: 1
      slurm_cpus_per_task: 4
      slurm_time: "00:10:00"
      modules: climacommon/2024_10_09