agents:
  queue: derecho
  # pbs_l_mem: 8G
  modules: climacommon/2024_05_27
  pbs_l_select: "1:ncpus=1"
  pbs_q: "develop"

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  CONFIG_PATH: "config/model_configs"
  GPU_CONFIG_PATH: "config/gpu_configs"
  PERF_CONFIG_PATH: "config/perf_configs"
  MPI_CONFIG_PATH: "config/mpi_configs"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    # concurrency: 1
    # concurrency_group: 'depot/climaatmos-ci'
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate examples"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate calibration/test"
      - "julia --project=calibration/test -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=calibration/test -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=calibration/test -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=examples artifacts/download_artifacts.jl"

    agents:
      pbs_l_select: "1:ncpus=8:ngpus=1"
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Reproducibility tests"
    steps:

      - label: ":computer: Ensure mse tables are reset when necessary"
        command: "julia --color=yes --project=examples reproducibility_tests/test_reset.jl"

  - group: "Radiation"
    steps:

      - label: ":computer: single column radiative equilibrium gray"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/single_column_radiative_equilibrium_gray.yml
          --job_id single_column_radiative_equilibrium_gray
        artifact_paths: "single_column_radiative_equilibrium_gray/output_active/*"

      - label: ":computer: single column radiative equilibrium clearsky"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/single_column_radiative_equilibrium_clearsky.yml
          --job_id single_column_radiative_equilibrium_clearsky
        artifact_paths: "single_column_radiative_equilibrium_clearsky/output_active/*"

      - label: ":computer: single column radiative equilibrium clearsky prognostic surface temperature"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/single_column_radiative_equilibrium_clearsky_prognostic_surface_temp.yml
          --job_id single_column_radiative_equilibrium_clearsky_prognostic_surface_temp
        artifact_paths: "single_column_radiative_equilibrium_clearsky_prognostic_surface_temp/output_active/*"

      - label: ":computer: single column radiative equilibrium allsky idealized clouds varying insolation"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/single_column_radiative_equilibrium_allsky_idealized_clouds.yml
          --job_id single_column_radiative_equilibrium_allsky_idealized_clouds
        artifact_paths: "single_column_radiative_equilibrium_allsky_idealized_clouds/output_active/*"

  - group: "Precipitation"
    steps:
      - label: ":umbrella: 1-moment precipitation sanity test single column"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/single_column_precipitation_test.yml
          --job_id single_column_precipitation_test
        artifact_paths: "single_column_precipitation_test/output_active/*"

  - group: "Column Examples"
    steps:

      - label: ":computer: single column hydrostatic balance float64"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/single_column_hydrostatic_balance_ft64.yml
          --job_id single_column_hydrostatic_balance_ft64
        artifact_paths: "single_column_hydrostatic_balance_ft64/output_active/*"

  - group: "Box Examples"
    steps:

      - label: ":computer: Box hydrostatic balance (ρe_tot)"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/box_hydrostatic_balance_rhoe.yml
          --job_id box_hydrostatic_balance_rhoe
        artifact_paths: "box_hydrostatic_balance_rhoe/output_active/*"

      - label: ":computer: 3D density current"
        command: >
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file $CONFIG_PATH/box_density_current_test.yml
          --job_id box_density_current_test
        artifact_paths: "box_density_current_test/output_active/*"
