env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path = \".\")'"
      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate examples"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=examples artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Regression tests"
    steps:

      - label: ":computer: Ensure mse tables are reset when necessary"
        command: "julia --color=yes --project=examples regression_tests/test_reset.jl"

  - group: "Sphere Examples (Dycore)"
    steps:

      - label: ":computer: no lim ARS baroclinic wave (ρe) equilmoist"
        command:
          - julia --color=yes --project=examples examples/hybrid/driver.jl --initial_condition MoistBaroclinicWave --moist equil --precip_model 0M --job_id sphere_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 450secs --dt_save_to_disk 2days --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_baroclinic_wave_rhoe_equilmoist --out_dir sphere_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_baroclinic_wave_rhoe_equilmoist --case_name moist_baroclinic_wave
          - julia --color=yes --project=examples regression_tests/test_mse.jl --job_id sphere_baroclinic_wave_rhoe_equilmoist --out_dir sphere_baroclinic_wave_rhoe_equilmoist
        artifact_paths: "sphere_baroclinic_wave_rhoe_equilmoist/*"

      - label: ":computer: SSP baroclinic wave (ρe_tot) equilmoist"
        command:
          - julia --color=yes --project=examples examples/hybrid/driver.jl --initial_condition MoistBaroclinicWave --moist equil --precip_model 0M --job_id sphere_ssp_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 450secs --dt_save_to_disk 2days --ode_algo SSP333
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_ssp_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples regression_tests/test_mse.jl --job_id sphere_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_ssp_baroclinic_wave_rhoe_equilmoist
        artifact_paths: "sphere_ssp_baroclinic_wave_rhoe_equilmoist/*"

      - label: ":computer: SSP 1st-order tracer upwind baroclinic wave (ρe_tot) equilmoist"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --job_id sphere_first_upwind_ssp_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 450secs --dt_save_to_disk 5days --ode_algo SSP333 --regression_test true --tracer_upwinding first_order"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_first_upwind_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_first_upwind_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_first_upwind_ssp_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_first_upwind_ssp_baroclinic_wave_rhoe_equilmoist --case_name moist_baroclinic_wave
        artifact_paths: "sphere_first_upwind_ssp_baroclinic_wave_rhoe_equilmoist/*"

      - label: ":computer: SSP zalesak tracer upwind baroclinic wave (ρe_tot) equilmoist"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --job_id sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 100secs --dt_save_to_disk 5days --ode_algo SSP333 --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --case_name moist_baroclinic_wave
        artifact_paths: "sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: explicit SSP zalesak tracer upwind baroclinic wave (ρe_tot) equilmoist"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --job_id sphere_explicit_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 25secs --dt_save_to_disk 5days --ode_algo SSP33ShuOsher --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_explicit_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_explicit_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_explicit_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_explicit_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --case_name moist_baroclinic_wave
        artifact_paths: "sphere_explicit_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: SSP zalesak all upwind baroclinic wave (ρe_tot) equilmoist"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --job_id sphere_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 100secs --dt_save_to_disk 5days --ode_algo SSP333 --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak --energy_upwinding zalesak --density_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --case_name moist_baroclinic_wave
        artifact_paths: "sphere_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: SSP explicit zalesak all upwind baroclinic wave (ρe_tot) equilmoist"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --job_id sphere_explicit_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --regression_test true --dt 25secs --dt_save_to_disk 5days --ode_algo SSP33ShuOsher --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak --energy_upwinding zalesak --density_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_explicit_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --out_dir sphere_explicit_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_explicit_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --fig_dir sphere_explicit_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist --case_name moist_baroclinic_wave
        artifact_paths: "sphere_explicit_zalesak_all_upwind_ssp_baroclinic_wave_rhoe_equilmoist/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: no lim ARS held suarez (ρe) equilmoist hightop sponge"
        command:
          - julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_held_suarez_rhoe_equilmoist_hightop_sponge --dt 450secs --t_end 4days --dt_save_to_disk 4days --regression_test true --apply_limiter false
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_held_suarez_rhoe_equilmoist_hightop_sponge
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_held_suarez_rhoe_equilmoist_hightop_sponge --fig_dir sphere_held_suarez_rhoe_equilmoist_hightop_sponge --case_name moist_held_suarez
          - julia --color=yes --project=examples regression_tests/test_mse.jl --job_id sphere_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_held_suarez_rhoe_equilmoist_hightop_sponge
        artifact_paths: "sphere_held_suarez_rhoe_equilmoist_hightop_sponge/*"

      - label: ":computer: SSP held suarez (ρe) equilmoist hightop sponge"
        command:
          - julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge --dt 450secs --t_end 5days --dt_save_to_disk 5days --regression_test true --ode_algo SSP333
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge --fig_dir sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge --case_name moist_held_suarez
          - julia --color=yes --project=examples regression_tests/test_mse.jl --job_id sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge
        artifact_paths: "sphere_ssp_held_suarez_rhoe_equilmoist_hightop_sponge/*"

      - label: ":computer: SSP 1st-order tracer upwind held suarez (ρe) equilmoist hightop sponge"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_ssp_first_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --dt 450secs --t_end 5days --dt_save_to_disk 5days --ode_algo SSP333 --regression_test true --tracer_upwinding first_order"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_ssp_first_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_ssp_first_upwind_held_suarez_rhoe_equilmoist_hightop_sponge
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_ssp_first_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --fig_dir sphere_ssp_first_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --case_name moist_held_suarez
        artifact_paths: "sphere_ssp_first_upwind_held_suarez_rhoe_equilmoist_hightop_sponge/*"

      - label: ":computer: SSP zalesak tracer upwind held suarez (ρe) equilmoist hightop sponge"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --dt 100secs --t_end 5days --dt_save_to_disk 5days --ode_algo SSP333 --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --fig_dir sphere_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --case_name moist_held_suarez
        artifact_paths: "sphere_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: explicit SSP zalesak tracer upwind held suarez (ρe) equilmoist hightop sponge"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_explicit_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --dt 25secs --t_end 5days --dt_save_to_disk 5days --ode_algo SSP33ShuOsher --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_explicit_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_explicit_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge
        artifact_paths: "sphere_explicit_ssp_zalesak_upwind_held_suarez_rhoe_equilmoist_hightop_sponge/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: SSP zalesak all upwind held suarez (ρe) equilmoist hightop sponge"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_ssp_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --dt 100secs --t_end 5days --dt_save_to_disk 5days --ode_algo SSP333 --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak --energy_upwinding zalesak --density_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_ssp_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_ssp_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_ssp_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --fig_dir sphere_ssp_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --case_name moist_held_suarez
        artifact_paths: "sphere_ssp_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge/*"
        agents:
          slurm_mem: 20GB

      - label: ":computer: SSP explicit zalesak all upwind held suarez (ρe) equilmoist hightop sponge"
        command:
          - "julia --color=yes --project=examples examples/hybrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_ssp_explicit_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --dt 25secs --t_end 5days --dt_save_to_disk 5days --ode_algo SSP33ShuOsher --max_newton_iters 6 --regression_test true --tracer_upwinding zalesak --energy_upwinding zalesak --density_upwinding zalesak"
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir sphere_ssp_explicit_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --out_dir sphere_ssp_explicit_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir sphere_ssp_explicit_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --fig_dir sphere_ssp_explicit_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --case_name moist_held_suarez
        artifact_paths: "sphere_ssp_explicit_zalesak_all_upwind_held_suarez_rhoe_equilmoist_hightop_sponge/*"
        agents:
          slurm_mem: 20GB

  - wait: ~
    continue_on_failure: true

  - label: ":robot_face: Print new mse tables"
    command: "julia --color=yes --project=examples regression_tests/print_new_mse.jl"

  - label: ":robot_face: Print new reference counter"
    command: "julia --color=yes --project=examples regression_tests/print_new_ref_counter.jl"

  - label: ":bar_chart: Tabulate performance summary"
    command: "julia --color=yes --project=perf perf/tabulate_perf_summary.jl"

  - label: ":chart_with_downwards_trend: build history"
    command:
      - build_history main
    artifact_paths:
      - "build_history.html"

  - wait

  - label: ":robot_face: Move main results"
    command: "julia --color=yes --project=examples regression_tests/move_output.jl"
