agents:
  queue: clima
  slurm_mem: 8G
  modules: julia/1.10.5 cuda/julia-pref openmpi/4.1.5-mpitrampoline nsight-systems/2024.6.1

env:
  JULIA_MPI_HAS_CUDA: "true"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  GPU_CONFIG_PATH: "config/gpu_configs/"
  MODEL_CONFIG_PATH: "config/model_configs/"
  CLIMAATMOS_GC_NSTEPS: 10

steps:
  - label: "Check GPU environment"
    command:
      - echo "--- Basic environment check"
      - env | grep CUDA_VISIBLE_DEVICES
      - env | grep SLURM_STEP_GPUS
      - echo "--- MPI rank GPU visibility"
      - mpiexec -n 2 bash -c "echo $OMPI_COMM_WORLD_RANK"
      - mpiexec -n 2 bash -c "echo $CUDA_VISIBLE_DEVICES"
      - echo "--- GPU Status"
      - nvidia-smi
      - echo "--- SLURM GPU info"
      - env | grep SLURM | grep -i gpu
    env:
      CLIMACOMMS_DEVICE: "CUDA"
      CLIMACOMMS_CONTEXT: "MPI"
    agents:
      slurm_gpus_per_task: 1
      slurm_cpus_per_task: 4
      slurm_ntasks: 2
      slurm_mem: 1G
      slurm_time: 0:10:00
      slurm_exclusive:
