agents:
  queue: clima
  slurm_mem: 8G
  modules: julia/1.10.0 cuda/julia-pref openmpi/4.1.5-mpitrampoline nsight-systems/2024.2.1

env:
  JULIA_MPI_HAS_CUDA: "true"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  GPU_CONFIG_PATH: "config/gpu_configs/"
  MODEL_CONFIG_PATH: "config/model_configs/"
  CONFIG_PATH: "config/longrun_configs"
  CLIMAATMOS_GC_NSTEPS: 10

timeout_in_minutes: 1440

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate examples"
      - julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - "julia --project=examples -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.add(url = \"https://github.com/CLiMA/ClimaCore.jl\", rev = \"as/covar-deriv\");'"
      - julia --project=examples -e 'using Pkg; Pkg.precompile()'
      - julia --project=examples -e 'using CUDA; CUDA.precompile_runtime()'
      - julia --project=examples -e 'using Pkg; Pkg.status()'

      - echo "--- Download artifacts"
      - julia --project=examples artifacts/download_artifacts.jl

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "les test"
    steps:
      
      - label: "dycoms: 2 GPUs"
        command:
          - >
            srun --cpu-bind=threads --cpus-per-task=4
            julia --threads=3 --color=yes --project=examples examples/hybrid/driver.jl
            --config_file config/model_configs/les_dycoms_box.yml
            --job_id dycoms
        artifact_paths: "dycoms/output_active/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16G
          slurm_time: 6:00:00
      
      - label: "bomex: 2 GPUs"
        command:
          - >
            srun --cpu-bind=threads --cpus-per-task=4
            julia --threads=3 --color=yes --project=examples examples/hybrid/driver.jl
            --config_file config/model_configs/les_bomex_box.yml
            --job_id bomex
        artifact_paths: "bomex/output_active/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16G
          slurm_time: 6:00:00
      
      - label: "rico: 2 GPUs"
        command:
          - >
            srun --cpu-bind=threads --cpus-per-task=4
            julia --threads=3 --color=yes --project=examples examples/hybrid/driver.jl
            --config_file config/model_configs/les_rico_box.yml
            --job_id rico
        artifact_paths: "rico/output_active/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16G
          slurm_time: 6:00:00
