agents:
  queue: clima
  slurm_mem: 8G
  modules: julia/1.9.3 cuda/julia-pref openmpi/4.1.5-cuda

env:
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GPU_CONFIG_PATH: "config/gpu_configs/"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Configure CUDA"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

      - echo "--- Instantiate examples"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=examples artifacts/download_artifacts.jl"
    agents:
      slurm_gpus: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "GPU target simulations"
    steps:

      - label: "target_gpu_implicit_baroclinic_wave"
        command: >
          julia --project -e 'using CUDA; CUDA.versioninfo()'
          
          nsys profile --trace=nvtx,cuda --output=target_gpu_implicit_baroclinic_wave/report
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file ${GPU_CONFIG_PATH}target_gpu_implicit_baroclinic_wave.yml
        artifact_paths: "target_gpu_implicit_baroclinic_wave/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "gpu_hs_rhoe_equilmoist_nz63_0M_55km_rs35km"
        command: >
          julia --project -e 'using CUDA; CUDA.versioninfo()'
          
          nsys profile --trace=nvtx,cuda --output=gpu_hs_rhoe_equilmoist_nz63_0M_55km_rs35km/report
          julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file ${GPU_CONFIG_PATH}gpu_hs_rhoe_equilmoist_nz63_0M_55km_rs35km.yml
        artifact_paths: "gpu_hs_rhoe_equilmoist_nz63_0M_55km_rs35km/*"
        agents:
          slurm_gpus: 1
          slurm_time: 23:00:00

      - label: "target_gpu_implicit_baroclinic_wave_4process"
        command: >
          julia --project -e 'using CUDA; CUDA.versioninfo()'
          
          nsys profile --trace=nvtx,cuda --output=target_gpu_implicit_baroclinic_wave_4process/report
          mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl
          --config_file ${GPU_CONFIG_PATH}target_gpu_implicit_baroclinic_wave_4process.yml
        artifact_paths: "target_gpu_implicit_baroclinic_wave_4process/*"
        agents:
          slurm_gpus_per_task: 1
          slurm_ntasks: 4
