agents:
  queue: clima
  slurm_mem: 8G
  modules: climacommon/2024_12_16 nsight-systems/2024.6.1

env:
  JULIA_MPI_HAS_CUDA: "true"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  GPU_CONFIG_PATH: "config/gpu_configs/"
  MODEL_CONFIG_PATH: "config/model_configs/"
  CLIMAATMOS_GC_NSTEPS: 10

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate examples"
      - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=.buildkite -e 'using Pkg; Pkg.precompile()'
      - julia --project=.buildkite -e 'using CUDA; CUDA.precompile_runtime()'
      - julia --project=.buildkite -e 'using Pkg; Pkg.status()'

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "GPU target simulations"
    steps:

      - label: "moist Held-Suarez"
        key: "gpu_hs_rhoe_equil_55km_nz63_0M"
        command:
          - mkdir -p gpu_hs_rhoe_equil_55km_nz63_0M
          - >
            nsys profile --delay 100 --trace=nvtx,mpi,cuda,osrt --output=gpu_hs_rhoe_equil_55km_nz63_0M/output_active/report
            julia --threads=3 --color=yes --project=.buildkite .buildkite/ci_driver.jl
            --config_file ${GPU_CONFIG_PATH}gpu_hs_rhoe_equil_0M.yml
            --job_id gpu_hs_rhoe_equil_55km_nz63_0M
        artifact_paths: "gpu_hs_rhoe_equil_55km_nz63_0M/output_active/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1
          slurm_cpus_per_task: 4
          slurm_exclusive:

