dt: "80secs"
apply_limiter: true
ode_algo: ARS343
hyperdiff: "CAM_SE"
dt_save_to_disk: "10days"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
kappa_4: 2.0e16
vert_diff: "true"
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
forcing: "held_suarez"
job_id: "dt_ARS_lim_CD_80secs"
