dt_save_state_to_disk: "Inf"
dt_save_to_sol: "Inf"
h_elem: 60
z_max: 60000.0
z_elem: 63
dz_bottom: 30.0
rayleigh_sponge: true
viscous_sponge: true
moist: "equil"
precip_model: "0M"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
vert_diff: "DecayWithHeightDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
surface_setup: "DefaultMoninObukhov"
dt: "60secs"
t_end: "10days"
toml: [toml/longrun_aquaplanet.toml]
# prescribe_ozone: true
# aerosol_radiation: true
# prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
start_date: "20160801"
initial_condition: "artifact\"DYAMOND_SUMMER_ICS_p98deg\"/DYAMOND_SUMMER_ICS_p98deg.nc"
#initial_condition: "/Users/zshen/Work/clima_repo/artifacts/dyamond_3dz.nc"
topography: "Earth"
netcdf_interpolation_num_points: [720, 360, 63]
diagnostics:
  - short_name: [ts, ta, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hfes, evspsbl, pr]
    period: "1days"
