sleve_eta: 0.7
surface_thermo_state_type: "GCMSurfaceThermoState"
external_forcing_file: ~
topo_smoothing: false
hyperdiff: "CAM_SE"
dt: "2000secs"
output_dir: "calibration_end_to_end_test"
prognostic_tke: false
override_Ï„_precip: true
use_newton_rtol: false
netcdf_output_at_levels: true
output_dir_style: "ActiveLink"
external_forcing: ~
device: "auto"
t_end: "30days"
dz_top: 5000.0
y_elem: 6
z_stretch: true
bubble: true
ode_algo: "SSPKnoth"
max_newton_iters_ode: 1
start_date: "20050117"
forcing: ~
edmfx_nh_pressure: false
scalar_hyperdiffusion_coefficient: 1.5
prognostic_surface: false
test_dycore_consistency: false
add_isothermal_boundary_layer: true
restart_file: ~
rad: "clearsky"
edmf_coriolis: ~
moist: "dry"
rayleigh_sponge: false
initial_condition: "DecayingProfile"
cloud_model: "quadrature"
krylov_rtol: 0.1
divergence_damping_factor: 1.0
edmfx_entr_model: ~
eisenstat_walker_forcing_alpha: 2.0
dt_cloud_fraction: "3hours"
smoothing_order: 3
idealized_h2o: false
surface_setup: "DefaultExchangeCoefficients"
perturb_initstate: true
implicit_sgs_advection: false
jvp_step_adjustment: 1.0
discrete_hydrostatic_balance: false
insolation: "timevarying"
log_progress: true
dz_bottom: 500.0
h_elem: 1
dt_save_state_to_disk: "Inf"
netcdf_interpolation_num_points: ~
advection_test: false
z_max: 30000.0
apply_limiter: false
topography: "NoWarp"
aerosol_radiation: false
reference_job_id: ~
precip_model: ~
vorticity_hyperdiffusion_coefficient: 1.5
perf_summary: false
call_cloud_diagnostics_per_stage: false
viscous_sponge: false
surface_temperature: "ZonallySymmetric"
edmfx_filter: false
diagnostics:
  - reduction_time: "average"
    short_name: "rsut"
    period: "30days"
    writer: "nc"
orographic_gravity_wave: ~
dt_rad: "6hours"
approximate_linear_solve_iters: 1
edmfx_upwinding: "none"
tracer_upwinding: "none"
enable_diagnostics: true
nh_poly: 3
edmfx_sgs_diffusive_flux: false
y_max: 300000.0
non_orographic_gravity_wave: false
albedo_model: "ConstantAlbedo"
config: "column"
energy_upwinding: "none"
FLOAT_TYPE: "Float32"
deep_atmosphere: false
split_ode: true
updraft_number: 1
regression_test: false
check_conservation: false
ls_adv: ~
prescribed_aerosols: []
output_default_diagnostics: false
implicit_diffusion: false
x_max: 300000.0
edmfx_sgs_mass_flux: false
z_elem: 10
newton_rtol: 1.0e-5
edmfx_sgsflux_upwinding: "none"
turbconv: ~
x_elem: 6
idealized_clouds: false
vert_diff: false
check_nan_every: 1024
use_krylov_method: false
subsidence: ~
sleve_s: 10.0
use_dynamic_krylov_rtol: false
toml: []
mesh_warp_type: "Linear"
edmfx_detr_model: ~
zero_tendency: ~
dt_save_to_sol: "1days"
