name: lookahead

# This action sets up a couple of tests for newer versions of julia and for
# dependencies more recent than the one in examples so that one can see if there
# are upcoming problems.

on:
  push:
    tags: '*'
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.9'
          - '~1.10.0-rc1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Instantiate test env
        run: |
          julia --project=test -e "using Pkg; Pkg.instantiate(); Pkg.develop(path=\".\")"
      - name: Run test_env.yml
        continue-on-error: true
        run: |
          julia --project=test examples/hybrid/driver.jl --config_file config/model_configs/test_env.yml
      - name: Run tests
        run: |
          julia --project=test test/runtests.jl
